/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package cross_call_worker */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "autoexports.go"
#include "autoexports.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void __NoParamReturnVoid(void);
extern GoUint8 __NoParamReturnBool(void);
extern GoInt8 __NoParamReturnChar8(void);
extern GoUint16 __NoParamReturnChar16(void);
extern GoInt8 __NoParamReturnInt8(void);
extern GoInt16 __NoParamReturnInt16(void);
extern GoInt32 __NoParamReturnInt32(void);
extern GoInt64 __NoParamReturnInt64(void);
extern GoUint8 __NoParamReturnUInt8(void);
extern GoUint16 __NoParamReturnUInt16(void);
extern GoUint32 __NoParamReturnUInt32(void);
extern GoUint64 __NoParamReturnUInt64(void);
extern GoUintptr __NoParamReturnPointer(void);
extern GoFloat32 __NoParamReturnFloat(void);
extern GoFloat64 __NoParamReturnDouble(void);
extern void* __NoParamReturnFunction(void);
extern String __NoParamReturnString(void);
extern Variant __NoParamReturnAny(void);
extern Vector __NoParamReturnArrayBool(void);
extern Vector __NoParamReturnArrayChar8(void);
extern Vector __NoParamReturnArrayChar16(void);
extern Vector __NoParamReturnArrayInt8(void);
extern Vector __NoParamReturnArrayInt16(void);
extern Vector __NoParamReturnArrayInt32(void);
extern Vector __NoParamReturnArrayInt64(void);
extern Vector __NoParamReturnArrayUInt8(void);
extern Vector __NoParamReturnArrayUInt16(void);
extern Vector __NoParamReturnArrayUInt32(void);
extern Vector __NoParamReturnArrayUInt64(void);
extern Vector __NoParamReturnArrayPointer(void);
extern Vector __NoParamReturnArrayFloat(void);
extern Vector __NoParamReturnArrayDouble(void);
extern Vector __NoParamReturnArrayString(void);
extern Vector __NoParamReturnArrayAny(void);
extern Vector __NoParamReturnArrayVector2(void);
extern Vector __NoParamReturnArrayVector3(void);
extern Vector __NoParamReturnArrayVector4(void);
extern Vector __NoParamReturnArrayMatrix4x4(void);
extern Vector2 __NoParamReturnVector2(void);
extern Vector3 __NoParamReturnVector3(void);
extern Vector4 __NoParamReturnVector4(void);
extern Matrix4x4 __NoParamReturnMatrix4x4(void);
extern void __Param1(GoInt32 a);
extern void __Param2(GoInt32 a, GoFloat32 b);
extern void __Param3(GoInt32 a, GoFloat32 b, GoFloat64 c);
extern void __Param4(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d);
extern void __Param5(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e);
extern void __Param6(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f);
extern void __Param7(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g);
extern void __Param8(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h);
extern void __Param9(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h, GoInt16 k);
extern void __Param10(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h, GoInt16 k, GoUintptr l);
extern void __ParamRef1(GoInt32* a);
extern void __ParamRef2(GoInt32* a, GoFloat32* b);
extern void __ParamRef3(GoInt32* a, GoFloat32* b, GoFloat64* c);
extern void __ParamRef4(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d);
extern void __ParamRef5(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e);
extern void __ParamRef6(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f);
extern void __ParamRef7(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g);
extern void __ParamRef8(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h);
extern void __ParamRef9(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h, GoInt16* k);
extern void __ParamRef10(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h, GoInt16* k, GoUintptr* l);
extern void __ParamRefVectors(Vector* p1, Vector* p2, Vector* p3, Vector* p4, Vector* p5, Vector* p6, Vector* p7, Vector* p8, Vector* p9, Vector* p10, Vector* p11, Vector* p12, Vector* p13, Vector* p14, Vector* p15);
extern GoInt64 __ParamAllPrimitives(GoUint8 p1, GoInt8 p2, GoUint16 p3, GoInt8 p4, GoInt16 p5, GoInt32 p6, GoInt64 p7, GoUint8 p8, GoUint16 p9, GoUint32 p10, GoUint64 p11, GoUintptr p12, GoFloat32 p13, GoFloat64 p14);
extern GoInt32 __ParamAllAliases(GoUint8 aBool, GoInt8 aChar8, GoUint16 aChar16, GoInt8 aInt8, GoInt16 aInt16, GoInt32 aInt32, GoInt64 aInt64, GoUintptr aPtr, GoFloat32 aFloat, GoFloat64 aDouble, String* aString, Variant* aAny, Vector2* aVec2, Vector3* aVec3, Vector4* aVec4, Matrix4x4* aMat4x4, Vector* aBoolVec, Vector* aChar8Vec, Vector* aChar16Vec, Vector* aInt8Vec, Vector* aInt16Vec, Vector* aInt32Vec, Vector* aInt64Vec, Vector* aPtrVec, Vector* aFloatVec, Vector* aDoubleVec, Vector* aStringVec, Vector* aAnyVec, Vector* aVec2Vec, Vector* aVec3Vec, Vector* aVec4Vec);
extern GoInt64 __ParamAllRefAliases(GoUint8* aBool, GoInt8* aChar8, GoUint16* aChar16, GoInt8* aInt8, GoInt16* aInt16, GoInt32* aInt32, GoInt64* aInt64, GoUintptr* aPtr, GoFloat32* aFloat, GoFloat64* aDouble, String* aString, Variant* aAny, Vector2* aVec2, Vector3* aVec3, Vector4* aVec4, Matrix4x4* aMat4x4, Vector* aBoolVec, Vector* aChar8Vec, Vector* aChar16Vec, Vector* aInt8Vec, Vector* aInt16Vec, Vector* aInt32Vec, Vector* aInt64Vec, Vector* aPtrVec, Vector* aFloatVec, Vector* aDoubleVec, Vector* aStringVec, Vector* aAnyVec, Vector* aVec2Vec, Vector* aVec3Vec, Vector* aVec4Vec);
extern GoInt32 __ParamEnum(GoInt32 p1, Vector* p2);
extern GoInt32 __ParamEnumRef(GoInt32* p1, Vector* p2);
extern void __ParamVariant(Variant* p1, Vector* p2);
extern void __ParamVariantRef(Variant* p1, Vector* p2);
extern void __CallFuncVoid(void* func_);
extern GoUint8 __CallFuncBool(void* func_);
extern GoInt8 __CallFuncChar8(void* func_);
extern GoUint16 __CallFuncChar16(void* func_);
extern GoInt8 __CallFuncInt8(void* func_);
extern GoInt16 __CallFuncInt16(void* func_);
extern GoInt32 __CallFuncInt32(void* func_);
extern GoInt64 __CallFuncInt64(void* func_);
extern GoUint8 __CallFuncUInt8(void* func_);
extern GoUint16 __CallFuncUInt16(void* func_);
extern GoUint32 __CallFuncUInt32(void* func_);
extern GoUint64 __CallFuncUInt64(void* func_);
extern GoUintptr __CallFuncPtr(void* func_);
extern GoFloat32 __CallFuncFloat(void* func_);
extern GoFloat64 __CallFuncDouble(void* func_);
extern void* __CallFuncFunction(void* func_);
extern String __CallFuncString(void* func_);
extern Variant __CallFuncAny(void* func_);
extern Vector __CallFuncBoolVector(void* func_);
extern Vector __CallFuncChar8Vector(void* func_);
extern Vector __CallFuncChar16Vector(void* func_);
extern Vector __CallFuncInt8Vector(void* func_);
extern Vector __CallFuncInt16Vector(void* func_);
extern Vector __CallFuncInt32Vector(void* func_);
extern Vector __CallFuncInt64Vector(void* func_);
extern Vector __CallFuncUInt8Vector(void* func_);
extern Vector __CallFuncUInt16Vector(void* func_);
extern Vector __CallFuncUInt32Vector(void* func_);
extern Vector __CallFuncUInt64Vector(void* func_);
extern Vector __CallFuncPtrVector(void* func_);
extern Vector __CallFuncFloatVector(void* func_);
extern Vector __CallFuncDoubleVector(void* func_);
extern Vector __CallFuncStringVector(void* func_);
extern Vector __CallFuncAnyVector(void* func_);
extern Vector __CallFuncVec2Vector(void* func_);
extern Vector __CallFuncVec3Vector(void* func_);
extern Vector __CallFuncVec4Vector(void* func_);
extern Vector __CallFuncMat4x4Vector(void* func_);
extern Vector2 __CallFuncVec2(void* func_);
extern Vector3 __CallFuncVec3(void* func_);
extern Vector4 __CallFuncVec4(void* func_);
extern Matrix4x4 __CallFuncMat4x4(void* func_);
extern GoInt32 __CallFunc1(void* func_);
extern GoInt8 __CallFunc2(void* func_);
extern void __CallFunc3(void* func_);
extern Vector4 __CallFunc4(void* func_);
extern GoUint8 __CallFunc5(void* func_);
extern GoInt64 __CallFunc6(void* func_);
extern GoFloat64 __CallFunc7(void* func_);
extern Matrix4x4 __CallFunc8(void* func_);
extern void __CallFunc9(void* func_);
extern GoUint32 __CallFunc10(void* func_);
extern GoUintptr __CallFunc11(void* func_);
extern GoUint8 __CallFunc12(void* func_);
extern String __CallFunc13(void* func_);
extern Vector __CallFunc14(void* func_);
extern GoInt16 __CallFunc15(void* func_);
extern GoUintptr __CallFunc16(void* func_);
extern String __CallFunc17(void* func_);
extern String __CallFunc18(void* func_);
extern String __CallFunc19(void* func_);
extern String __CallFunc20(void* func_);
extern String __CallFunc21(void* func_);
extern String __CallFunc22(void* func_);
extern String __CallFunc23(void* func_);
extern String __CallFunc24(void* func_);
extern String __CallFunc25(void* func_);
extern String __CallFunc26(void* func_);
extern String __CallFunc27(void* func_);
extern String __CallFunc28(void* func_);
extern String __CallFunc29(void* func_);
extern String __CallFunc30(void* func_);
extern String __CallFunc31(void* func_);
extern String __CallFunc32(void* func_);
extern String __CallFunc33(void* func_);
extern String __CallFuncEnum(void* func_);
extern GoUint8 __CallFuncAliasBool(void* func_);
extern GoInt8 __CallFuncAliasChar8(void* func_);
extern GoUint16 __CallFuncAliasChar16(void* func_);
extern GoInt8 __CallFuncAliasInt8(void* func_);
extern GoInt16 __CallFuncAliasInt16(void* func_);
extern GoInt32 __CallFuncAliasInt32(void* func_);
extern GoInt64 __CallFuncAliasInt64(void* func_);
extern GoUint8 __CallFuncAliasUInt8(void* func_);
extern GoUint16 __CallFuncAliasUInt16(void* func_);
extern GoUint32 __CallFuncAliasUInt32(void* func_);
extern GoUint64 __CallFuncAliasUInt64(void* func_);
extern GoUintptr __CallFuncAliasPtr(void* func_);
extern GoFloat32 __CallFuncAliasFloat(void* func_);
extern GoFloat64 __CallFuncAliasDouble(void* func_);
extern GoUintptr __CallFuncAliasFunction(void* func_);
extern String __CallFuncAliasString(void* func_);
extern Variant __CallFuncAliasAny(void* func_);
extern Vector __CallFuncAliasBoolVector(void* func_);
extern Vector __CallFuncAliasChar8Vector(void* func_);
extern Vector __CallFuncAliasChar16Vector(void* func_);
extern Vector __CallFuncAliasInt8Vector(void* func_);
extern Vector __CallFuncAliasInt16Vector(void* func_);
extern Vector __CallFuncAliasInt32Vector(void* func_);
extern Vector __CallFuncAliasInt64Vector(void* func_);
extern Vector __CallFuncAliasUInt8Vector(void* func_);
extern Vector __CallFuncAliasUInt16Vector(void* func_);
extern Vector __CallFuncAliasUInt32Vector(void* func_);
extern Vector __CallFuncAliasUInt64Vector(void* func_);
extern Vector __CallFuncAliasPtrVector(void* func_);
extern Vector __CallFuncAliasFloatVector(void* func_);
extern Vector __CallFuncAliasDoubleVector(void* func_);
extern Vector __CallFuncAliasStringVector(void* func_);
extern Vector __CallFuncAliasAnyVector(void* func_);
extern Vector __CallFuncAliasVec2Vector(void* func_);
extern Vector __CallFuncAliasVec3Vector(void* func_);
extern Vector __CallFuncAliasVec4Vector(void* func_);
extern Vector __CallFuncAliasMat4x4Vector(void* func_);
extern Vector2 __CallFuncAliasVec2(void* func_);
extern Vector3 __CallFuncAliasVec3(void* func_);
extern Vector4 __CallFuncAliasVec4(void* func_);
extern Matrix4x4 __CallFuncAliasMat4x4(void* func_);
extern String __CallFuncAliasAll(void* func_);
extern String __ReverseNoParamReturnVoid(void);
extern String __ReverseNoParamReturnBool(void);
extern String __ReverseNoParamReturnChar8(void);
extern String __ReverseNoParamReturnChar16(void);
extern String __ReverseNoParamReturnInt8(void);
extern String __ReverseNoParamReturnInt16(void);
extern String __ReverseNoParamReturnInt32(void);
extern String __ReverseNoParamReturnInt64(void);
extern String __ReverseNoParamReturnUInt8(void);
extern String __ReverseNoParamReturnUInt16(void);
extern String __ReverseNoParamReturnUInt32(void);
extern String __ReverseNoParamReturnUInt64(void);
extern String __ReverseNoParamReturnPointer(void);
extern String __ReverseNoParamReturnFloat(void);
extern String __ReverseNoParamReturnDouble(void);
extern String __ReverseNoParamReturnFunction(void);
extern String __ReverseNoParamReturnString(void);
extern String __ReverseNoParamReturnAny(void);
extern String __ReverseNoParamReturnArrayBool(void);
extern String __ReverseNoParamReturnArrayChar8(void);
extern String __ReverseNoParamReturnArrayChar16(void);
extern String __ReverseNoParamReturnArrayInt8(void);
extern String __ReverseNoParamReturnArrayInt16(void);
extern String __ReverseNoParamReturnArrayInt32(void);
extern String __ReverseNoParamReturnArrayInt64(void);
extern String __ReverseNoParamReturnArrayUInt8(void);
extern String __ReverseNoParamReturnArrayUInt16(void);
extern String __ReverseNoParamReturnArrayUInt32(void);
extern String __ReverseNoParamReturnArrayUInt64(void);
extern String __ReverseNoParamReturnArrayPointer(void);
extern String __ReverseNoParamReturnArrayFloat(void);
extern String __ReverseNoParamReturnArrayDouble(void);
extern String __ReverseNoParamReturnArrayString(void);
extern String __ReverseNoParamReturnArrayAny(void);
extern String __ReverseNoParamReturnVector2(void);
extern String __ReverseNoParamReturnVector3(void);
extern String __ReverseNoParamReturnVector4(void);
extern String __ReverseNoParamReturnMatrix4x4(void);
extern String __ReverseParam1(void);
extern String __ReverseParam2(void);
extern String __ReverseParam3(void);
extern String __ReverseParam4(void);
extern String __ReverseParam5(void);
extern String __ReverseParam6(void);
extern String __ReverseParam7(void);
extern String __ReverseParam8(void);
extern String __ReverseParam9(void);
extern String __ReverseParam10(void);
extern String __ReverseParamRef1(void);
extern String __ReverseParamRef2(void);
extern String __ReverseParamRef3(void);
extern String __ReverseParamRef4(void);
extern String __ReverseParamRef5(void);
extern String __ReverseParamRef6(void);
extern String __ReverseParamRef7(void);
extern String __ReverseParamRef8(void);
extern String __ReverseParamRef9(void);
extern String __ReverseParamRef10(void);
extern String __ReverseParamRefVectors(void);
extern String __ReverseParamAllPrimitives(void);
extern String __ReverseParamAllAliases(void);
extern String __ReverseParamAllRefAliases(void);
extern String __ReverseParamEnum(void);
extern String __ReverseParamEnumRef(void);
extern String __ReverseParamVariant(void);
extern String __ReverseParamVariantRef(void);
extern String __ReverseCallFuncVoid(void);
extern String __ReverseCallFuncBool(void);
extern String __ReverseCallFuncChar8(void);
extern String __ReverseCallFuncChar16(void);
extern String __ReverseCallFuncInt8(void);
extern String __ReverseCallFuncInt16(void);
extern String __ReverseCallFuncInt32(void);
extern String __ReverseCallFuncInt64(void);
extern String __ReverseCallFuncUInt8(void);
extern String __ReverseCallFuncUInt16(void);
extern String __ReverseCallFuncUInt32(void);
extern String __ReverseCallFuncUInt64(void);
extern String __ReverseCallFuncPtr(void);
extern String __ReverseCallFuncFloat(void);
extern String __ReverseCallFuncDouble(void);
extern String __ReverseCallFuncString(void);
extern String __ReverseCallFuncAny(void);
extern String __ReverseCallFuncBoolVector(void);
extern String __ReverseCallFuncChar8Vector(void);
extern String __ReverseCallFuncChar16Vector(void);
extern String __ReverseCallFuncInt8Vector(void);
extern String __ReverseCallFuncInt16Vector(void);
extern String __ReverseCallFuncInt32Vector(void);
extern String __ReverseCallFuncInt64Vector(void);
extern String __ReverseCallFuncUInt8Vector(void);
extern String __ReverseCallFuncUInt16Vector(void);
extern String __ReverseCallFuncUInt32Vector(void);
extern String __ReverseCallFuncUInt64Vector(void);
extern String __ReverseCallFuncPtrVector(void);
extern String __ReverseCallFuncFloatVector(void);
extern String __ReverseCallFuncDoubleVector(void);
extern String __ReverseCallFuncStringVector(void);
extern String __ReverseCallFuncAnyVector(void);
extern String __ReverseCallFuncVec2Vector(void);
extern String __ReverseCallFuncVec3Vector(void);
extern String __ReverseCallFuncVec4Vector(void);
extern String __ReverseCallFuncMat4x4Vector(void);
extern String __ReverseCallFuncVec2(void);
extern String __ReverseCallFuncVec3(void);
extern String __ReverseCallFuncVec4(void);
extern String __ReverseCallFuncMat4x4(void);
extern String __ReverseCallFuncAliasBool(void);
extern String __ReverseCallFuncAliasChar8(void);
extern String __ReverseCallFuncAliasChar16(void);
extern String __ReverseCallFuncAliasInt8(void);
extern String __ReverseCallFuncAliasInt16(void);
extern String __ReverseCallFuncAliasInt32(void);
extern String __ReverseCallFuncAliasInt64(void);
extern String __ReverseCallFuncAliasUInt8(void);
extern String __ReverseCallFuncAliasUInt16(void);
extern String __ReverseCallFuncAliasUInt32(void);
extern String __ReverseCallFuncAliasUInt64(void);
extern String __ReverseCallFuncAliasPtr(void);
extern String __ReverseCallFuncAliasFloat(void);
extern String __ReverseCallFuncAliasDouble(void);
extern String __ReverseCallFuncAliasString(void);
extern String __ReverseCallFuncAliasAny(void);
extern String __ReverseCallFuncAliasBoolVector(void);
extern String __ReverseCallFuncAliasChar8Vector(void);
extern String __ReverseCallFuncAliasChar16Vector(void);
extern String __ReverseCallFuncAliasInt8Vector(void);
extern String __ReverseCallFuncAliasInt16Vector(void);
extern String __ReverseCallFuncAliasInt32Vector(void);
extern String __ReverseCallFuncAliasInt64Vector(void);
extern String __ReverseCallFuncAliasUInt8Vector(void);
extern String __ReverseCallFuncAliasUInt16Vector(void);
extern String __ReverseCallFuncAliasUInt32Vector(void);
extern String __ReverseCallFuncAliasUInt64Vector(void);
extern String __ReverseCallFuncAliasPtrVector(void);
extern String __ReverseCallFuncAliasFloatVector(void);
extern String __ReverseCallFuncAliasDoubleVector(void);
extern String __ReverseCallFuncAliasStringVector(void);
extern String __ReverseCallFuncAliasAnyVector(void);
extern String __ReverseCallFuncAliasVec2Vector(void);
extern String __ReverseCallFuncAliasVec3Vector(void);
extern String __ReverseCallFuncAliasVec4Vector(void);
extern String __ReverseCallFuncAliasMat4x4Vector(void);
extern String __ReverseCallFuncAliasVec2(void);
extern String __ReverseCallFuncAliasVec3(void);
extern String __ReverseCallFuncAliasVec4(void);
extern String __ReverseCallFuncAliasMat4x4(void);
extern String __ReverseCallFuncAliasAll(void);
extern String __ReverseCallFunc1(void);
extern String __ReverseCallFunc2(void);
extern String __ReverseCallFunc3(void);
extern String __ReverseCallFunc4(void);
extern String __ReverseCallFunc5(void);
extern String __ReverseCallFunc6(void);
extern String __ReverseCallFunc7(void);
extern String __ReverseCallFunc8(void);
extern String __ReverseCallFunc9(void);
extern String __ReverseCallFunc10(void);
extern String __ReverseCallFunc11(void);
extern String __ReverseCallFunc12(void);
extern String __ReverseCallFunc13(void);
extern String __ReverseCallFunc14(void);
extern String __ReverseCallFunc15(void);
extern String __ReverseCallFunc16(void);
extern String __ReverseCallFunc17(void);
extern String __ReverseCallFunc18(void);
extern String __ReverseCallFunc19(void);
extern String __ReverseCallFunc20(void);
extern String __ReverseCallFunc21(void);
extern String __ReverseCallFunc22(void);
extern String __ReverseCallFunc23(void);
extern String __ReverseCallFunc24(void);
extern String __ReverseCallFunc25(void);
extern String __ReverseCallFunc26(void);
extern String __ReverseCallFunc27(void);
extern String __ReverseCallFunc28(void);
extern String __ReverseCallFunc29(void);
extern String __ReverseCallFunc30(void);
extern String __ReverseCallFunc31(void);
extern String __ReverseCallFunc32(void);
extern String __ReverseCallFunc33(void);
extern String __ReverseCallFuncEnum(void);
extern void __ReverseCall(String* test);

#ifdef __cplusplus
}
#endif
