/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package plugify-plugin */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "autoexports.go"
 #include "autoexports.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void __NoParamReturnVoid();
extern __declspec(dllexport) GoUint8 __NoParamReturnBool();
extern __declspec(dllexport) GoInt8 __NoParamReturnChar8();
extern __declspec(dllexport) GoUint16 __NoParamReturnChar16();
extern __declspec(dllexport) GoInt8 __NoParamReturnInt8();
extern __declspec(dllexport) GoInt16 __NoParamReturnInt16();
extern __declspec(dllexport) GoInt32 __NoParamReturnInt32();
extern __declspec(dllexport) GoInt64 __NoParamReturnInt64();
extern __declspec(dllexport) GoUint8 __NoParamReturnUInt8();
extern __declspec(dllexport) GoUint16 __NoParamReturnUInt16();
extern __declspec(dllexport) GoUint32 __NoParamReturnUInt32();
extern __declspec(dllexport) GoUint64 __NoParamReturnUInt64();
extern __declspec(dllexport) GoUintptr __NoParamReturnPointer();
extern __declspec(dllexport) GoFloat32 __NoParamReturnFloat();
extern __declspec(dllexport) GoFloat64 __NoParamReturnDouble();
extern __declspec(dllexport) void* __NoParamReturnFunction();
extern __declspec(dllexport) String __NoParamReturnString();
extern __declspec(dllexport) Variant __NoParamReturnAny();
extern __declspec(dllexport) Vector __NoParamReturnArrayBool();
extern __declspec(dllexport) Vector __NoParamReturnArrayChar8();
extern __declspec(dllexport) Vector __NoParamReturnArrayChar16();
extern __declspec(dllexport) Vector __NoParamReturnArrayInt8();
extern __declspec(dllexport) Vector __NoParamReturnArrayInt16();
extern __declspec(dllexport) Vector __NoParamReturnArrayInt32();
extern __declspec(dllexport) Vector __NoParamReturnArrayInt64();
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt8();
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt16();
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt32();
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt64();
extern __declspec(dllexport) Vector __NoParamReturnArrayPointer();
extern __declspec(dllexport) Vector __NoParamReturnArrayFloat();
extern __declspec(dllexport) Vector __NoParamReturnArrayDouble();
extern __declspec(dllexport) Vector __NoParamReturnArrayString();
extern __declspec(dllexport) Vector __NoParamReturnArrayAny();
extern __declspec(dllexport) Vector __NoParamReturnArrayVector2();
extern __declspec(dllexport) Vector __NoParamReturnArrayVector3();
extern __declspec(dllexport) Vector __NoParamReturnArrayVector4();
extern __declspec(dllexport) Vector __NoParamReturnArrayMatrix4x4();
extern __declspec(dllexport) Vector2 __NoParamReturnVector2();
extern __declspec(dllexport) Vector3 __NoParamReturnVector3();
extern __declspec(dllexport) Vector4 __NoParamReturnVector4();
extern __declspec(dllexport) Matrix4x4 __NoParamReturnMatrix4x4();
extern __declspec(dllexport) void __Param1(GoInt32 a);
extern __declspec(dllexport) void __Param2(GoInt32 a, GoFloat32 b);
extern __declspec(dllexport) void __Param3(GoInt32 a, GoFloat32 b, GoFloat64 c);
extern __declspec(dllexport) void __Param4(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d);
extern __declspec(dllexport) void __Param5(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e);
extern __declspec(dllexport) void __Param6(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f);
extern __declspec(dllexport) void __Param7(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g);
extern __declspec(dllexport) void __Param8(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h);
extern __declspec(dllexport) void __Param9(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h, GoInt16 k);
extern __declspec(dllexport) void __Param10(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h, GoInt16 k, GoUintptr l);
extern __declspec(dllexport) void __ParamRef1(GoInt32* a);
extern __declspec(dllexport) void __ParamRef2(GoInt32* a, GoFloat32* b);
extern __declspec(dllexport) void __ParamRef3(GoInt32* a, GoFloat32* b, GoFloat64* c);
extern __declspec(dllexport) void __ParamRef4(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d);
extern __declspec(dllexport) void __ParamRef5(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e);
extern __declspec(dllexport) void __ParamRef6(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f);
extern __declspec(dllexport) void __ParamRef7(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g);
extern __declspec(dllexport) void __ParamRef8(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h);
extern __declspec(dllexport) void __ParamRef9(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h, GoInt16* k);
extern __declspec(dllexport) void __ParamRef10(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h, GoInt16* k, GoUintptr* l);
extern __declspec(dllexport) void __ParamRefVectors(Vector* p1, Vector* p2, Vector* p3, Vector* p4, Vector* p5, Vector* p6, Vector* p7, Vector* p8, Vector* p9, Vector* p10, Vector* p11, Vector* p12, Vector* p13, Vector* p14, Vector* p15);
extern __declspec(dllexport) GoInt64 __ParamAllPrimitives(GoUint8 p1, GoInt8 p2, GoUint16 p3, GoInt8 p4, GoInt16 p5, GoInt32 p6, GoInt64 p7, GoUint8 p8, GoUint16 p9, GoUint32 p10, GoUint64 p11, GoUintptr p12, GoFloat32 p13, GoFloat64 p14);
extern __declspec(dllexport) void __ParamVariant(Variant* p1, Vector* p2);
extern __declspec(dllexport) GoInt32 __ParamEnum(GoInt32 p1, Vector* p2);
extern __declspec(dllexport) GoInt32 __ParamEnumRef(GoInt32* p1, Vector* p2);
extern __declspec(dllexport) void __ParamVariantRef(Variant* p1, Vector* p2);
extern __declspec(dllexport) void __CallFuncVoid(void* func_);
extern __declspec(dllexport) GoUint8 __CallFuncBool(void* func_);
extern __declspec(dllexport) GoInt8 __CallFuncChar8(void* func_);
extern __declspec(dllexport) GoUint16 __CallFuncChar16(void* func_);
extern __declspec(dllexport) GoInt8 __CallFuncInt8(void* func_);
extern __declspec(dllexport) GoInt16 __CallFuncInt16(void* func_);
extern __declspec(dllexport) GoInt32 __CallFuncInt32(void* func_);
extern __declspec(dllexport) GoInt64 __CallFuncInt64(void* func_);
extern __declspec(dllexport) GoUint8 __CallFuncUInt8(void* func_);
extern __declspec(dllexport) GoUint16 __CallFuncUInt16(void* func_);
extern __declspec(dllexport) GoUint32 __CallFuncUInt32(void* func_);
extern __declspec(dllexport) GoUint64 __CallFuncUInt64(void* func_);
extern __declspec(dllexport) GoUintptr __CallFuncPtr(void* func_);
extern __declspec(dllexport) GoFloat32 __CallFuncFloat(void* func_);
extern __declspec(dllexport) GoFloat64 __CallFuncDouble(void* func_);
extern __declspec(dllexport) String __CallFuncString(void* func_);
extern __declspec(dllexport) Variant __CallFuncAny(void* func_);
extern __declspec(dllexport) GoUintptr __CallFuncFunction(void* func_);
extern __declspec(dllexport) Vector __CallFuncBoolVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncChar8Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncChar16Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt8Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt16Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt32Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt64Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt8Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt16Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt32Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt64Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncPtrVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncFloatVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncDoubleVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncStringVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncAnyVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncVec2Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncVec3Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncVec4Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncMat4x4Vector(void* func_);
extern __declspec(dllexport) Vector2 __CallFuncVec2(void* func_);
extern __declspec(dllexport) Vector3 __CallFuncVec3(void* func_);
extern __declspec(dllexport) Vector4 __CallFuncVec4(void* func_);
extern __declspec(dllexport) Matrix4x4 __CallFuncMat4x4(void* func_);
extern __declspec(dllexport) GoInt32 __CallFunc1(void* func_);
extern __declspec(dllexport) GoInt8 __CallFunc2(void* func_);
extern __declspec(dllexport) void __CallFunc3(void* func_);
extern __declspec(dllexport) Vector4 __CallFunc4(void* func_);
extern __declspec(dllexport) GoUint8 __CallFunc5(void* func_);
extern __declspec(dllexport) GoInt64 __CallFunc6(void* func_);
extern __declspec(dllexport) GoFloat64 __CallFunc7(void* func_);
extern __declspec(dllexport) Matrix4x4 __CallFunc8(void* func_);
extern __declspec(dllexport) void __CallFunc9(void* func_);
extern __declspec(dllexport) GoUint32 __CallFunc10(void* func_);
extern __declspec(dllexport) GoUintptr __CallFunc11(void* func_);
extern __declspec(dllexport) GoUint8 __CallFunc12(void* func_);
extern __declspec(dllexport) String __CallFunc13(void* func_);
extern __declspec(dllexport) Vector __CallFunc14(void* func_);
extern __declspec(dllexport) GoInt16 __CallFunc15(void* func_);
extern __declspec(dllexport) GoUintptr __CallFunc16(void* func_);
extern __declspec(dllexport) String __CallFunc17(void* func_);
extern __declspec(dllexport) String __CallFunc18(void* func_);
extern __declspec(dllexport) String __CallFunc19(void* func_);
extern __declspec(dllexport) String __CallFunc20(void* func_);
extern __declspec(dllexport) String __CallFunc21(void* func_);
extern __declspec(dllexport) String __CallFunc22(void* func_);
extern __declspec(dllexport) String __CallFunc23(void* func_);
extern __declspec(dllexport) String __CallFunc24(void* func_);
extern __declspec(dllexport) String __CallFunc25(void* func_);
extern __declspec(dllexport) String __CallFunc26(void* func_);
extern __declspec(dllexport) String __CallFunc27(void* func_);
extern __declspec(dllexport) String __CallFunc28(void* func_);
extern __declspec(dllexport) String __CallFunc29(void* func_);
extern __declspec(dllexport) String __CallFunc30(void* func_);
extern __declspec(dllexport) String __CallFunc31(void* func_);
extern __declspec(dllexport) String __CallFunc32(void* func_);
extern __declspec(dllexport) String __CallFunc33(void* func_);
extern __declspec(dllexport) String __CallFuncEnum(void* func_);
extern __declspec(dllexport) void __ReverseCall(String* test);

#ifdef __cplusplus
}
#endif
