//go:build plugin
// +build plugin

package main

//TODO: replace "cross_call_worker" by your package name
import (
	"cross_call_worker/cross_call_master"
	"unsafe"

	"github.com/untrustedmodders/go-plugify"
)

var _ = unsafe.Sizeof(0)
var _ = plugify.ApiVersion

//go:linkname cross_call_master_ReverseReturn cross_call_worker/cross_call_master._ReverseReturn
var cross_call_master_ReverseReturn func(returnString string)
var Cross_call_master_ReverseReturn = &cross_call_master_ReverseReturn

//go:linkname cross_call_master_NoParamReturnVoidCallback cross_call_worker/cross_call_master._NoParamReturnVoidCallback
var cross_call_master_NoParamReturnVoidCallback func()
var Cross_call_master_NoParamReturnVoidCallback = &cross_call_master_NoParamReturnVoidCallback

//go:linkname cross_call_master_NoParamReturnBoolCallback cross_call_worker/cross_call_master._NoParamReturnBoolCallback
var cross_call_master_NoParamReturnBoolCallback func() bool
var Cross_call_master_NoParamReturnBoolCallback = &cross_call_master_NoParamReturnBoolCallback

//go:linkname cross_call_master_NoParamReturnChar8Callback cross_call_worker/cross_call_master._NoParamReturnChar8Callback
var cross_call_master_NoParamReturnChar8Callback func() int8
var Cross_call_master_NoParamReturnChar8Callback = &cross_call_master_NoParamReturnChar8Callback

//go:linkname cross_call_master_NoParamReturnChar16Callback cross_call_worker/cross_call_master._NoParamReturnChar16Callback
var cross_call_master_NoParamReturnChar16Callback func() uint16
var Cross_call_master_NoParamReturnChar16Callback = &cross_call_master_NoParamReturnChar16Callback

//go:linkname cross_call_master_NoParamReturnInt8Callback cross_call_worker/cross_call_master._NoParamReturnInt8Callback
var cross_call_master_NoParamReturnInt8Callback func() int8
var Cross_call_master_NoParamReturnInt8Callback = &cross_call_master_NoParamReturnInt8Callback

//go:linkname cross_call_master_NoParamReturnInt16Callback cross_call_worker/cross_call_master._NoParamReturnInt16Callback
var cross_call_master_NoParamReturnInt16Callback func() int16
var Cross_call_master_NoParamReturnInt16Callback = &cross_call_master_NoParamReturnInt16Callback

//go:linkname cross_call_master_NoParamReturnInt32Callback cross_call_worker/cross_call_master._NoParamReturnInt32Callback
var cross_call_master_NoParamReturnInt32Callback func() int32
var Cross_call_master_NoParamReturnInt32Callback = &cross_call_master_NoParamReturnInt32Callback

//go:linkname cross_call_master_NoParamReturnInt64Callback cross_call_worker/cross_call_master._NoParamReturnInt64Callback
var cross_call_master_NoParamReturnInt64Callback func() int64
var Cross_call_master_NoParamReturnInt64Callback = &cross_call_master_NoParamReturnInt64Callback

//go:linkname cross_call_master_NoParamReturnUInt8Callback cross_call_worker/cross_call_master._NoParamReturnUInt8Callback
var cross_call_master_NoParamReturnUInt8Callback func() uint8
var Cross_call_master_NoParamReturnUInt8Callback = &cross_call_master_NoParamReturnUInt8Callback

//go:linkname cross_call_master_NoParamReturnUInt16Callback cross_call_worker/cross_call_master._NoParamReturnUInt16Callback
var cross_call_master_NoParamReturnUInt16Callback func() uint16
var Cross_call_master_NoParamReturnUInt16Callback = &cross_call_master_NoParamReturnUInt16Callback

//go:linkname cross_call_master_NoParamReturnUInt32Callback cross_call_worker/cross_call_master._NoParamReturnUInt32Callback
var cross_call_master_NoParamReturnUInt32Callback func() uint32
var Cross_call_master_NoParamReturnUInt32Callback = &cross_call_master_NoParamReturnUInt32Callback

//go:linkname cross_call_master_NoParamReturnUInt64Callback cross_call_worker/cross_call_master._NoParamReturnUInt64Callback
var cross_call_master_NoParamReturnUInt64Callback func() uint64
var Cross_call_master_NoParamReturnUInt64Callback = &cross_call_master_NoParamReturnUInt64Callback

//go:linkname cross_call_master_NoParamReturnPointerCallback cross_call_worker/cross_call_master._NoParamReturnPointerCallback
var cross_call_master_NoParamReturnPointerCallback func() uintptr
var Cross_call_master_NoParamReturnPointerCallback = &cross_call_master_NoParamReturnPointerCallback

//go:linkname cross_call_master_NoParamReturnFloatCallback cross_call_worker/cross_call_master._NoParamReturnFloatCallback
var cross_call_master_NoParamReturnFloatCallback func() float32
var Cross_call_master_NoParamReturnFloatCallback = &cross_call_master_NoParamReturnFloatCallback

//go:linkname cross_call_master_NoParamReturnDoubleCallback cross_call_worker/cross_call_master._NoParamReturnDoubleCallback
var cross_call_master_NoParamReturnDoubleCallback func() float64
var Cross_call_master_NoParamReturnDoubleCallback = &cross_call_master_NoParamReturnDoubleCallback

//go:linkname cross_call_master_NoParamReturnFunctionCallback cross_call_worker/cross_call_master._NoParamReturnFunctionCallback
var cross_call_master_NoParamReturnFunctionCallback func() cross_call_master.NoParamReturnFunctionCallbackFunc
var Cross_call_master_NoParamReturnFunctionCallback = &cross_call_master_NoParamReturnFunctionCallback

//go:linkname cross_call_master_NoParamReturnStringCallback cross_call_worker/cross_call_master._NoParamReturnStringCallback
var cross_call_master_NoParamReturnStringCallback func() string
var Cross_call_master_NoParamReturnStringCallback = &cross_call_master_NoParamReturnStringCallback

//go:linkname cross_call_master_NoParamReturnAnyCallback cross_call_worker/cross_call_master._NoParamReturnAnyCallback
var cross_call_master_NoParamReturnAnyCallback func() any
var Cross_call_master_NoParamReturnAnyCallback = &cross_call_master_NoParamReturnAnyCallback

//go:linkname cross_call_master_NoParamReturnArrayBoolCallback cross_call_worker/cross_call_master._NoParamReturnArrayBoolCallback
var cross_call_master_NoParamReturnArrayBoolCallback func() []bool
var Cross_call_master_NoParamReturnArrayBoolCallback = &cross_call_master_NoParamReturnArrayBoolCallback

//go:linkname cross_call_master_NoParamReturnArrayChar8Callback cross_call_worker/cross_call_master._NoParamReturnArrayChar8Callback
var cross_call_master_NoParamReturnArrayChar8Callback func() []int8
var Cross_call_master_NoParamReturnArrayChar8Callback = &cross_call_master_NoParamReturnArrayChar8Callback

//go:linkname cross_call_master_NoParamReturnArrayChar16Callback cross_call_worker/cross_call_master._NoParamReturnArrayChar16Callback
var cross_call_master_NoParamReturnArrayChar16Callback func() []uint16
var Cross_call_master_NoParamReturnArrayChar16Callback = &cross_call_master_NoParamReturnArrayChar16Callback

//go:linkname cross_call_master_NoParamReturnArrayInt8Callback cross_call_worker/cross_call_master._NoParamReturnArrayInt8Callback
var cross_call_master_NoParamReturnArrayInt8Callback func() []int8
var Cross_call_master_NoParamReturnArrayInt8Callback = &cross_call_master_NoParamReturnArrayInt8Callback

//go:linkname cross_call_master_NoParamReturnArrayInt16Callback cross_call_worker/cross_call_master._NoParamReturnArrayInt16Callback
var cross_call_master_NoParamReturnArrayInt16Callback func() []int16
var Cross_call_master_NoParamReturnArrayInt16Callback = &cross_call_master_NoParamReturnArrayInt16Callback

//go:linkname cross_call_master_NoParamReturnArrayInt32Callback cross_call_worker/cross_call_master._NoParamReturnArrayInt32Callback
var cross_call_master_NoParamReturnArrayInt32Callback func() []int32
var Cross_call_master_NoParamReturnArrayInt32Callback = &cross_call_master_NoParamReturnArrayInt32Callback

//go:linkname cross_call_master_NoParamReturnArrayInt64Callback cross_call_worker/cross_call_master._NoParamReturnArrayInt64Callback
var cross_call_master_NoParamReturnArrayInt64Callback func() []int64
var Cross_call_master_NoParamReturnArrayInt64Callback = &cross_call_master_NoParamReturnArrayInt64Callback

//go:linkname cross_call_master_NoParamReturnArrayUInt8Callback cross_call_worker/cross_call_master._NoParamReturnArrayUInt8Callback
var cross_call_master_NoParamReturnArrayUInt8Callback func() []uint8
var Cross_call_master_NoParamReturnArrayUInt8Callback = &cross_call_master_NoParamReturnArrayUInt8Callback

//go:linkname cross_call_master_NoParamReturnArrayUInt16Callback cross_call_worker/cross_call_master._NoParamReturnArrayUInt16Callback
var cross_call_master_NoParamReturnArrayUInt16Callback func() []uint16
var Cross_call_master_NoParamReturnArrayUInt16Callback = &cross_call_master_NoParamReturnArrayUInt16Callback

//go:linkname cross_call_master_NoParamReturnArrayUInt32Callback cross_call_worker/cross_call_master._NoParamReturnArrayUInt32Callback
var cross_call_master_NoParamReturnArrayUInt32Callback func() []uint32
var Cross_call_master_NoParamReturnArrayUInt32Callback = &cross_call_master_NoParamReturnArrayUInt32Callback

//go:linkname cross_call_master_NoParamReturnArrayUInt64Callback cross_call_worker/cross_call_master._NoParamReturnArrayUInt64Callback
var cross_call_master_NoParamReturnArrayUInt64Callback func() []uint64
var Cross_call_master_NoParamReturnArrayUInt64Callback = &cross_call_master_NoParamReturnArrayUInt64Callback

//go:linkname cross_call_master_NoParamReturnArrayPointerCallback cross_call_worker/cross_call_master._NoParamReturnArrayPointerCallback
var cross_call_master_NoParamReturnArrayPointerCallback func() []uintptr
var Cross_call_master_NoParamReturnArrayPointerCallback = &cross_call_master_NoParamReturnArrayPointerCallback

//go:linkname cross_call_master_NoParamReturnArrayFloatCallback cross_call_worker/cross_call_master._NoParamReturnArrayFloatCallback
var cross_call_master_NoParamReturnArrayFloatCallback func() []float32
var Cross_call_master_NoParamReturnArrayFloatCallback = &cross_call_master_NoParamReturnArrayFloatCallback

//go:linkname cross_call_master_NoParamReturnArrayDoubleCallback cross_call_worker/cross_call_master._NoParamReturnArrayDoubleCallback
var cross_call_master_NoParamReturnArrayDoubleCallback func() []float64
var Cross_call_master_NoParamReturnArrayDoubleCallback = &cross_call_master_NoParamReturnArrayDoubleCallback

//go:linkname cross_call_master_NoParamReturnArrayStringCallback cross_call_worker/cross_call_master._NoParamReturnArrayStringCallback
var cross_call_master_NoParamReturnArrayStringCallback func() []string
var Cross_call_master_NoParamReturnArrayStringCallback = &cross_call_master_NoParamReturnArrayStringCallback

//go:linkname cross_call_master_NoParamReturnArrayAnyCallback cross_call_worker/cross_call_master._NoParamReturnArrayAnyCallback
var cross_call_master_NoParamReturnArrayAnyCallback func() []any
var Cross_call_master_NoParamReturnArrayAnyCallback = &cross_call_master_NoParamReturnArrayAnyCallback

//go:linkname cross_call_master_NoParamReturnArrayVector2Callback cross_call_worker/cross_call_master._NoParamReturnArrayVector2Callback
var cross_call_master_NoParamReturnArrayVector2Callback func() []plugify.Vector2
var Cross_call_master_NoParamReturnArrayVector2Callback = &cross_call_master_NoParamReturnArrayVector2Callback

//go:linkname cross_call_master_NoParamReturnArrayVector3Callback cross_call_worker/cross_call_master._NoParamReturnArrayVector3Callback
var cross_call_master_NoParamReturnArrayVector3Callback func() []plugify.Vector3
var Cross_call_master_NoParamReturnArrayVector3Callback = &cross_call_master_NoParamReturnArrayVector3Callback

//go:linkname cross_call_master_NoParamReturnArrayVector4Callback cross_call_worker/cross_call_master._NoParamReturnArrayVector4Callback
var cross_call_master_NoParamReturnArrayVector4Callback func() []plugify.Vector4
var Cross_call_master_NoParamReturnArrayVector4Callback = &cross_call_master_NoParamReturnArrayVector4Callback

//go:linkname cross_call_master_NoParamReturnArrayMatrix4x4Callback cross_call_worker/cross_call_master._NoParamReturnArrayMatrix4x4Callback
var cross_call_master_NoParamReturnArrayMatrix4x4Callback func() []plugify.Matrix4x4
var Cross_call_master_NoParamReturnArrayMatrix4x4Callback = &cross_call_master_NoParamReturnArrayMatrix4x4Callback

//go:linkname cross_call_master_NoParamReturnVector2Callback cross_call_worker/cross_call_master._NoParamReturnVector2Callback
var cross_call_master_NoParamReturnVector2Callback func() plugify.Vector2
var Cross_call_master_NoParamReturnVector2Callback = &cross_call_master_NoParamReturnVector2Callback

//go:linkname cross_call_master_NoParamReturnVector3Callback cross_call_worker/cross_call_master._NoParamReturnVector3Callback
var cross_call_master_NoParamReturnVector3Callback func() plugify.Vector3
var Cross_call_master_NoParamReturnVector3Callback = &cross_call_master_NoParamReturnVector3Callback

//go:linkname cross_call_master_NoParamReturnVector4Callback cross_call_worker/cross_call_master._NoParamReturnVector4Callback
var cross_call_master_NoParamReturnVector4Callback func() plugify.Vector4
var Cross_call_master_NoParamReturnVector4Callback = &cross_call_master_NoParamReturnVector4Callback

//go:linkname cross_call_master_NoParamReturnMatrix4x4Callback cross_call_worker/cross_call_master._NoParamReturnMatrix4x4Callback
var cross_call_master_NoParamReturnMatrix4x4Callback func() plugify.Matrix4x4
var Cross_call_master_NoParamReturnMatrix4x4Callback = &cross_call_master_NoParamReturnMatrix4x4Callback

//go:linkname cross_call_master_Param1Callback cross_call_worker/cross_call_master._Param1Callback
var cross_call_master_Param1Callback func(a int32)
var Cross_call_master_Param1Callback = &cross_call_master_Param1Callback

//go:linkname cross_call_master_Param2Callback cross_call_worker/cross_call_master._Param2Callback
var cross_call_master_Param2Callback func(a int32, b float32)
var Cross_call_master_Param2Callback = &cross_call_master_Param2Callback

//go:linkname cross_call_master_Param3Callback cross_call_worker/cross_call_master._Param3Callback
var cross_call_master_Param3Callback func(a int32, b float32, c float64)
var Cross_call_master_Param3Callback = &cross_call_master_Param3Callback

//go:linkname cross_call_master_Param4Callback cross_call_worker/cross_call_master._Param4Callback
var cross_call_master_Param4Callback func(a int32, b float32, c float64, d plugify.Vector4)
var Cross_call_master_Param4Callback = &cross_call_master_Param4Callback

//go:linkname cross_call_master_Param5Callback cross_call_worker/cross_call_master._Param5Callback
var cross_call_master_Param5Callback func(a int32, b float32, c float64, d plugify.Vector4, e []int64)
var Cross_call_master_Param5Callback = &cross_call_master_Param5Callback

//go:linkname cross_call_master_Param6Callback cross_call_worker/cross_call_master._Param6Callback
var cross_call_master_Param6Callback func(a int32, b float32, c float64, d plugify.Vector4, e []int64, f int8)
var Cross_call_master_Param6Callback = &cross_call_master_Param6Callback

//go:linkname cross_call_master_Param7Callback cross_call_worker/cross_call_master._Param7Callback
var cross_call_master_Param7Callback func(a int32, b float32, c float64, d plugify.Vector4, e []int64, f int8, g string)
var Cross_call_master_Param7Callback = &cross_call_master_Param7Callback

//go:linkname cross_call_master_Param8Callback cross_call_worker/cross_call_master._Param8Callback
var cross_call_master_Param8Callback func(a int32, b float32, c float64, d plugify.Vector4, e []int64, f int8, g string, h uint16)
var Cross_call_master_Param8Callback = &cross_call_master_Param8Callback

//go:linkname cross_call_master_Param9Callback cross_call_worker/cross_call_master._Param9Callback
var cross_call_master_Param9Callback func(a int32, b float32, c float64, d plugify.Vector4, e []int64, f int8, g string, h uint16, k int16)
var Cross_call_master_Param9Callback = &cross_call_master_Param9Callback

//go:linkname cross_call_master_Param10Callback cross_call_worker/cross_call_master._Param10Callback
var cross_call_master_Param10Callback func(a int32, b float32, c float64, d plugify.Vector4, e []int64, f int8, g string, h uint16, k int16, l uintptr)
var Cross_call_master_Param10Callback = &cross_call_master_Param10Callback

//go:linkname cross_call_master_ParamRef1Callback cross_call_worker/cross_call_master._ParamRef1Callback
var cross_call_master_ParamRef1Callback func(a *int32)
var Cross_call_master_ParamRef1Callback = &cross_call_master_ParamRef1Callback

//go:linkname cross_call_master_ParamRef2Callback cross_call_worker/cross_call_master._ParamRef2Callback
var cross_call_master_ParamRef2Callback func(a *int32, b *float32)
var Cross_call_master_ParamRef2Callback = &cross_call_master_ParamRef2Callback

//go:linkname cross_call_master_ParamRef3Callback cross_call_worker/cross_call_master._ParamRef3Callback
var cross_call_master_ParamRef3Callback func(a *int32, b *float32, c *float64)
var Cross_call_master_ParamRef3Callback = &cross_call_master_ParamRef3Callback

//go:linkname cross_call_master_ParamRef4Callback cross_call_worker/cross_call_master._ParamRef4Callback
var cross_call_master_ParamRef4Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4)
var Cross_call_master_ParamRef4Callback = &cross_call_master_ParamRef4Callback

//go:linkname cross_call_master_ParamRef5Callback cross_call_worker/cross_call_master._ParamRef5Callback
var cross_call_master_ParamRef5Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4, e *[]int64)
var Cross_call_master_ParamRef5Callback = &cross_call_master_ParamRef5Callback

//go:linkname cross_call_master_ParamRef6Callback cross_call_worker/cross_call_master._ParamRef6Callback
var cross_call_master_ParamRef6Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4, e *[]int64, f *int8)
var Cross_call_master_ParamRef6Callback = &cross_call_master_ParamRef6Callback

//go:linkname cross_call_master_ParamRef7Callback cross_call_worker/cross_call_master._ParamRef7Callback
var cross_call_master_ParamRef7Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4, e *[]int64, f *int8, g *string)
var Cross_call_master_ParamRef7Callback = &cross_call_master_ParamRef7Callback

//go:linkname cross_call_master_ParamRef8Callback cross_call_worker/cross_call_master._ParamRef8Callback
var cross_call_master_ParamRef8Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4, e *[]int64, f *int8, g *string, h *uint16)
var Cross_call_master_ParamRef8Callback = &cross_call_master_ParamRef8Callback

//go:linkname cross_call_master_ParamRef9Callback cross_call_worker/cross_call_master._ParamRef9Callback
var cross_call_master_ParamRef9Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4, e *[]int64, f *int8, g *string, h *uint16, k *int16)
var Cross_call_master_ParamRef9Callback = &cross_call_master_ParamRef9Callback

//go:linkname cross_call_master_ParamRef10Callback cross_call_worker/cross_call_master._ParamRef10Callback
var cross_call_master_ParamRef10Callback func(a *int32, b *float32, c *float64, d *plugify.Vector4, e *[]int64, f *int8, g *string, h *uint16, k *int16, l *uintptr)
var Cross_call_master_ParamRef10Callback = &cross_call_master_ParamRef10Callback

//go:linkname cross_call_master_ParamRefVectorsCallback cross_call_worker/cross_call_master._ParamRefVectorsCallback
var cross_call_master_ParamRefVectorsCallback func(p1 *[]bool, p2 *[]int8, p3 *[]uint16, p4 *[]int8, p5 *[]int16, p6 *[]int32, p7 *[]int64, p8 *[]uint8, p9 *[]uint16, p10 *[]uint32, p11 *[]uint64, p12 *[]uintptr, p13 *[]float32, p14 *[]float64, p15 *[]string)
var Cross_call_master_ParamRefVectorsCallback = &cross_call_master_ParamRefVectorsCallback

//go:linkname cross_call_master_ParamAllPrimitivesCallback cross_call_worker/cross_call_master._ParamAllPrimitivesCallback
var cross_call_master_ParamAllPrimitivesCallback func(p1 bool, p2 int8, p3 uint16, p4 int8, p5 int16, p6 int32, p7 int64, p8 uint8, p9 uint16, p10 uint32, p11 uint64, p12 uintptr, p13 float32, p14 float64) int64
var Cross_call_master_ParamAllPrimitivesCallback = &cross_call_master_ParamAllPrimitivesCallback

//go:linkname cross_call_master_ParamAllAliasesCallback cross_call_worker/cross_call_master._ParamAllAliasesCallback
var cross_call_master_ParamAllAliasesCallback func(aBool cross_call_master.AliasBool, aChar8 cross_call_master.AliasChar8, aChar16 cross_call_master.AliasChar16, aInt8 cross_call_master.AliasInt8, aInt16 cross_call_master.AliasInt16, aInt32 cross_call_master.AliasInt32, aInt64 cross_call_master.AliasInt64, aPtr cross_call_master.AliasPtr, aFloat cross_call_master.AliasFloat, aDouble cross_call_master.AliasDouble, aString cross_call_master.AliasString, aAny cross_call_master.AliasAny, aVec2 cross_call_master.AliasVec2, aVec3 cross_call_master.AliasVec3, aVec4 cross_call_master.AliasVec4, aMat4x4 cross_call_master.AliasMat4x4, aBoolVec cross_call_master.AliasBoolVector, aChar8Vec cross_call_master.AliasChar8Vector, aChar16Vec cross_call_master.AliasChar16Vector, aInt8Vec cross_call_master.AliasInt8Vector, aInt16Vec cross_call_master.AliasInt16Vector, aInt32Vec cross_call_master.AliasInt32Vector, aInt64Vec cross_call_master.AliasInt64Vector, aPtrVec cross_call_master.AliasPtrVector, aFloatVec cross_call_master.AliasFloatVector, aDoubleVec cross_call_master.AliasDoubleVector, aStringVec cross_call_master.AliasStringVector, aAnyVec cross_call_master.AliasAnyVector, aVec2Vec cross_call_master.AliasVec2Vector, aVec3Vec cross_call_master.AliasVec3Vector, aVec4Vec cross_call_master.AliasVec4Vector) int32
var Cross_call_master_ParamAllAliasesCallback = &cross_call_master_ParamAllAliasesCallback

//go:linkname cross_call_master_ParamAllRefAliasesCallback cross_call_worker/cross_call_master._ParamAllRefAliasesCallback
var cross_call_master_ParamAllRefAliasesCallback func(aBool *cross_call_master.AliasBool, aChar8 *cross_call_master.AliasChar8, aChar16 *cross_call_master.AliasChar16, aInt8 *cross_call_master.AliasInt8, aInt16 *cross_call_master.AliasInt16, aInt32 *cross_call_master.AliasInt32, aInt64 *cross_call_master.AliasInt64, aPtr *cross_call_master.AliasPtr, aFloat *cross_call_master.AliasFloat, aDouble *cross_call_master.AliasDouble, aString *cross_call_master.AliasString, aAny *cross_call_master.AliasAny, aVec2 *cross_call_master.AliasVec2, aVec3 *cross_call_master.AliasVec3, aVec4 *cross_call_master.AliasVec4, aMat4x4 *cross_call_master.AliasMat4x4, aBoolVec *cross_call_master.AliasBoolVector, aChar8Vec *cross_call_master.AliasChar8Vector, aChar16Vec *cross_call_master.AliasChar16Vector, aInt8Vec *cross_call_master.AliasInt8Vector, aInt16Vec *cross_call_master.AliasInt16Vector, aInt32Vec *cross_call_master.AliasInt32Vector, aInt64Vec *cross_call_master.AliasInt64Vector, aPtrVec *cross_call_master.AliasPtrVector, aFloatVec *cross_call_master.AliasFloatVector, aDoubleVec *cross_call_master.AliasDoubleVector, aStringVec *cross_call_master.AliasStringVector, aAnyVec *cross_call_master.AliasAnyVector, aVec2Vec *cross_call_master.AliasVec2Vector, aVec3Vec *cross_call_master.AliasVec3Vector, aVec4Vec *cross_call_master.AliasVec4Vector) int64
var Cross_call_master_ParamAllRefAliasesCallback = &cross_call_master_ParamAllRefAliasesCallback

//go:linkname cross_call_master_ParamEnumCallback cross_call_worker/cross_call_master._ParamEnumCallback
var cross_call_master_ParamEnumCallback func(p1 cross_call_master.Example, p2 []cross_call_master.Example) int32
var Cross_call_master_ParamEnumCallback = &cross_call_master_ParamEnumCallback

//go:linkname cross_call_master_ParamEnumRefCallback cross_call_worker/cross_call_master._ParamEnumRefCallback
var cross_call_master_ParamEnumRefCallback func(p1 *cross_call_master.Example, p2 *[]cross_call_master.Example) int32
var Cross_call_master_ParamEnumRefCallback = &cross_call_master_ParamEnumRefCallback

//go:linkname cross_call_master_ParamVariantCallback cross_call_worker/cross_call_master._ParamVariantCallback
var cross_call_master_ParamVariantCallback func(p1 any, p2 []any)
var Cross_call_master_ParamVariantCallback = &cross_call_master_ParamVariantCallback

//go:linkname cross_call_master_ParamVariantRefCallback cross_call_worker/cross_call_master._ParamVariantRefCallback
var cross_call_master_ParamVariantRefCallback func(p1 *any, p2 *[]any)
var Cross_call_master_ParamVariantRefCallback = &cross_call_master_ParamVariantRefCallback

//go:linkname cross_call_master_CallFuncVoidCallback cross_call_worker/cross_call_master._CallFuncVoidCallback
var cross_call_master_CallFuncVoidCallback func(func_ cross_call_master.FuncVoid)
var Cross_call_master_CallFuncVoidCallback = &cross_call_master_CallFuncVoidCallback

//go:linkname cross_call_master_CallFuncBoolCallback cross_call_worker/cross_call_master._CallFuncBoolCallback
var cross_call_master_CallFuncBoolCallback func(func_ cross_call_master.FuncBool) bool
var Cross_call_master_CallFuncBoolCallback = &cross_call_master_CallFuncBoolCallback

//go:linkname cross_call_master_CallFuncChar8Callback cross_call_worker/cross_call_master._CallFuncChar8Callback
var cross_call_master_CallFuncChar8Callback func(func_ cross_call_master.FuncChar8) int8
var Cross_call_master_CallFuncChar8Callback = &cross_call_master_CallFuncChar8Callback

//go:linkname cross_call_master_CallFuncChar16Callback cross_call_worker/cross_call_master._CallFuncChar16Callback
var cross_call_master_CallFuncChar16Callback func(func_ cross_call_master.FuncChar16) uint16
var Cross_call_master_CallFuncChar16Callback = &cross_call_master_CallFuncChar16Callback

//go:linkname cross_call_master_CallFuncInt8Callback cross_call_worker/cross_call_master._CallFuncInt8Callback
var cross_call_master_CallFuncInt8Callback func(func_ cross_call_master.FuncInt8) int8
var Cross_call_master_CallFuncInt8Callback = &cross_call_master_CallFuncInt8Callback

//go:linkname cross_call_master_CallFuncInt16Callback cross_call_worker/cross_call_master._CallFuncInt16Callback
var cross_call_master_CallFuncInt16Callback func(func_ cross_call_master.FuncInt16) int16
var Cross_call_master_CallFuncInt16Callback = &cross_call_master_CallFuncInt16Callback

//go:linkname cross_call_master_CallFuncInt32Callback cross_call_worker/cross_call_master._CallFuncInt32Callback
var cross_call_master_CallFuncInt32Callback func(func_ cross_call_master.FuncInt32) int32
var Cross_call_master_CallFuncInt32Callback = &cross_call_master_CallFuncInt32Callback

//go:linkname cross_call_master_CallFuncInt64Callback cross_call_worker/cross_call_master._CallFuncInt64Callback
var cross_call_master_CallFuncInt64Callback func(func_ cross_call_master.FuncInt64) int64
var Cross_call_master_CallFuncInt64Callback = &cross_call_master_CallFuncInt64Callback

//go:linkname cross_call_master_CallFuncUInt8Callback cross_call_worker/cross_call_master._CallFuncUInt8Callback
var cross_call_master_CallFuncUInt8Callback func(func_ cross_call_master.FuncUInt8) uint8
var Cross_call_master_CallFuncUInt8Callback = &cross_call_master_CallFuncUInt8Callback

//go:linkname cross_call_master_CallFuncUInt16Callback cross_call_worker/cross_call_master._CallFuncUInt16Callback
var cross_call_master_CallFuncUInt16Callback func(func_ cross_call_master.FuncUInt16) uint16
var Cross_call_master_CallFuncUInt16Callback = &cross_call_master_CallFuncUInt16Callback

//go:linkname cross_call_master_CallFuncUInt32Callback cross_call_worker/cross_call_master._CallFuncUInt32Callback
var cross_call_master_CallFuncUInt32Callback func(func_ cross_call_master.FuncUInt32) uint32
var Cross_call_master_CallFuncUInt32Callback = &cross_call_master_CallFuncUInt32Callback

//go:linkname cross_call_master_CallFuncUInt64Callback cross_call_worker/cross_call_master._CallFuncUInt64Callback
var cross_call_master_CallFuncUInt64Callback func(func_ cross_call_master.FuncUInt64) uint64
var Cross_call_master_CallFuncUInt64Callback = &cross_call_master_CallFuncUInt64Callback

//go:linkname cross_call_master_CallFuncPtrCallback cross_call_worker/cross_call_master._CallFuncPtrCallback
var cross_call_master_CallFuncPtrCallback func(func_ cross_call_master.FuncPtr) uintptr
var Cross_call_master_CallFuncPtrCallback = &cross_call_master_CallFuncPtrCallback

//go:linkname cross_call_master_CallFuncFloatCallback cross_call_worker/cross_call_master._CallFuncFloatCallback
var cross_call_master_CallFuncFloatCallback func(func_ cross_call_master.FuncFloat) float32
var Cross_call_master_CallFuncFloatCallback = &cross_call_master_CallFuncFloatCallback

//go:linkname cross_call_master_CallFuncDoubleCallback cross_call_worker/cross_call_master._CallFuncDoubleCallback
var cross_call_master_CallFuncDoubleCallback func(func_ cross_call_master.FuncDouble) float64
var Cross_call_master_CallFuncDoubleCallback = &cross_call_master_CallFuncDoubleCallback

//go:linkname cross_call_master_CallFuncStringCallback cross_call_worker/cross_call_master._CallFuncStringCallback
var cross_call_master_CallFuncStringCallback func(func_ cross_call_master.FuncString) string
var Cross_call_master_CallFuncStringCallback = &cross_call_master_CallFuncStringCallback

//go:linkname cross_call_master_CallFuncAnyCallback cross_call_worker/cross_call_master._CallFuncAnyCallback
var cross_call_master_CallFuncAnyCallback func(func_ cross_call_master.FuncAny) any
var Cross_call_master_CallFuncAnyCallback = &cross_call_master_CallFuncAnyCallback

//go:linkname cross_call_master_CallFuncFunctionCallback cross_call_worker/cross_call_master._CallFuncFunctionCallback
var cross_call_master_CallFuncFunctionCallback func(func_ cross_call_master.FuncFunction) cross_call_master.FuncFunctionInner
var Cross_call_master_CallFuncFunctionCallback = &cross_call_master_CallFuncFunctionCallback

//go:linkname cross_call_master_CallFuncBoolVectorCallback cross_call_worker/cross_call_master._CallFuncBoolVectorCallback
var cross_call_master_CallFuncBoolVectorCallback func(func_ cross_call_master.FuncBoolVector) []bool
var Cross_call_master_CallFuncBoolVectorCallback = &cross_call_master_CallFuncBoolVectorCallback

//go:linkname cross_call_master_CallFuncChar8VectorCallback cross_call_worker/cross_call_master._CallFuncChar8VectorCallback
var cross_call_master_CallFuncChar8VectorCallback func(func_ cross_call_master.FuncChar8Vector) []int8
var Cross_call_master_CallFuncChar8VectorCallback = &cross_call_master_CallFuncChar8VectorCallback

//go:linkname cross_call_master_CallFuncChar16VectorCallback cross_call_worker/cross_call_master._CallFuncChar16VectorCallback
var cross_call_master_CallFuncChar16VectorCallback func(func_ cross_call_master.FuncChar16Vector) []uint16
var Cross_call_master_CallFuncChar16VectorCallback = &cross_call_master_CallFuncChar16VectorCallback

//go:linkname cross_call_master_CallFuncInt8VectorCallback cross_call_worker/cross_call_master._CallFuncInt8VectorCallback
var cross_call_master_CallFuncInt8VectorCallback func(func_ cross_call_master.FuncInt8Vector) []int8
var Cross_call_master_CallFuncInt8VectorCallback = &cross_call_master_CallFuncInt8VectorCallback

//go:linkname cross_call_master_CallFuncInt16VectorCallback cross_call_worker/cross_call_master._CallFuncInt16VectorCallback
var cross_call_master_CallFuncInt16VectorCallback func(func_ cross_call_master.FuncInt16Vector) []int16
var Cross_call_master_CallFuncInt16VectorCallback = &cross_call_master_CallFuncInt16VectorCallback

//go:linkname cross_call_master_CallFuncInt32VectorCallback cross_call_worker/cross_call_master._CallFuncInt32VectorCallback
var cross_call_master_CallFuncInt32VectorCallback func(func_ cross_call_master.FuncInt32Vector) []int32
var Cross_call_master_CallFuncInt32VectorCallback = &cross_call_master_CallFuncInt32VectorCallback

//go:linkname cross_call_master_CallFuncInt64VectorCallback cross_call_worker/cross_call_master._CallFuncInt64VectorCallback
var cross_call_master_CallFuncInt64VectorCallback func(func_ cross_call_master.FuncInt64Vector) []int64
var Cross_call_master_CallFuncInt64VectorCallback = &cross_call_master_CallFuncInt64VectorCallback

//go:linkname cross_call_master_CallFuncUInt8VectorCallback cross_call_worker/cross_call_master._CallFuncUInt8VectorCallback
var cross_call_master_CallFuncUInt8VectorCallback func(func_ cross_call_master.FuncUInt8Vector) []uint8
var Cross_call_master_CallFuncUInt8VectorCallback = &cross_call_master_CallFuncUInt8VectorCallback

//go:linkname cross_call_master_CallFuncUInt16VectorCallback cross_call_worker/cross_call_master._CallFuncUInt16VectorCallback
var cross_call_master_CallFuncUInt16VectorCallback func(func_ cross_call_master.FuncUInt16Vector) []uint16
var Cross_call_master_CallFuncUInt16VectorCallback = &cross_call_master_CallFuncUInt16VectorCallback

//go:linkname cross_call_master_CallFuncUInt32VectorCallback cross_call_worker/cross_call_master._CallFuncUInt32VectorCallback
var cross_call_master_CallFuncUInt32VectorCallback func(func_ cross_call_master.FuncUInt32Vector) []uint32
var Cross_call_master_CallFuncUInt32VectorCallback = &cross_call_master_CallFuncUInt32VectorCallback

//go:linkname cross_call_master_CallFuncUInt64VectorCallback cross_call_worker/cross_call_master._CallFuncUInt64VectorCallback
var cross_call_master_CallFuncUInt64VectorCallback func(func_ cross_call_master.FuncUInt64Vector) []uint64
var Cross_call_master_CallFuncUInt64VectorCallback = &cross_call_master_CallFuncUInt64VectorCallback

//go:linkname cross_call_master_CallFuncPtrVectorCallback cross_call_worker/cross_call_master._CallFuncPtrVectorCallback
var cross_call_master_CallFuncPtrVectorCallback func(func_ cross_call_master.FuncPtrVector) []uintptr
var Cross_call_master_CallFuncPtrVectorCallback = &cross_call_master_CallFuncPtrVectorCallback

//go:linkname cross_call_master_CallFuncFloatVectorCallback cross_call_worker/cross_call_master._CallFuncFloatVectorCallback
var cross_call_master_CallFuncFloatVectorCallback func(func_ cross_call_master.FuncFloatVector) []float32
var Cross_call_master_CallFuncFloatVectorCallback = &cross_call_master_CallFuncFloatVectorCallback

//go:linkname cross_call_master_CallFuncDoubleVectorCallback cross_call_worker/cross_call_master._CallFuncDoubleVectorCallback
var cross_call_master_CallFuncDoubleVectorCallback func(func_ cross_call_master.FuncDoubleVector) []float64
var Cross_call_master_CallFuncDoubleVectorCallback = &cross_call_master_CallFuncDoubleVectorCallback

//go:linkname cross_call_master_CallFuncStringVectorCallback cross_call_worker/cross_call_master._CallFuncStringVectorCallback
var cross_call_master_CallFuncStringVectorCallback func(func_ cross_call_master.FuncStringVector) []string
var Cross_call_master_CallFuncStringVectorCallback = &cross_call_master_CallFuncStringVectorCallback

//go:linkname cross_call_master_CallFuncAnyVectorCallback cross_call_worker/cross_call_master._CallFuncAnyVectorCallback
var cross_call_master_CallFuncAnyVectorCallback func(func_ cross_call_master.FuncAnyVector) []any
var Cross_call_master_CallFuncAnyVectorCallback = &cross_call_master_CallFuncAnyVectorCallback

//go:linkname cross_call_master_CallFuncVec2VectorCallback cross_call_worker/cross_call_master._CallFuncVec2VectorCallback
var cross_call_master_CallFuncVec2VectorCallback func(func_ cross_call_master.FuncVec2Vector) []plugify.Vector2
var Cross_call_master_CallFuncVec2VectorCallback = &cross_call_master_CallFuncVec2VectorCallback

//go:linkname cross_call_master_CallFuncVec3VectorCallback cross_call_worker/cross_call_master._CallFuncVec3VectorCallback
var cross_call_master_CallFuncVec3VectorCallback func(func_ cross_call_master.FuncVec3Vector) []plugify.Vector3
var Cross_call_master_CallFuncVec3VectorCallback = &cross_call_master_CallFuncVec3VectorCallback

//go:linkname cross_call_master_CallFuncVec4VectorCallback cross_call_worker/cross_call_master._CallFuncVec4VectorCallback
var cross_call_master_CallFuncVec4VectorCallback func(func_ cross_call_master.FuncVec4Vector) []plugify.Vector4
var Cross_call_master_CallFuncVec4VectorCallback = &cross_call_master_CallFuncVec4VectorCallback

//go:linkname cross_call_master_CallFuncMat4x4VectorCallback cross_call_worker/cross_call_master._CallFuncMat4x4VectorCallback
var cross_call_master_CallFuncMat4x4VectorCallback func(func_ cross_call_master.FuncMat4x4Vector) []plugify.Matrix4x4
var Cross_call_master_CallFuncMat4x4VectorCallback = &cross_call_master_CallFuncMat4x4VectorCallback

//go:linkname cross_call_master_CallFuncVec2Callback cross_call_worker/cross_call_master._CallFuncVec2Callback
var cross_call_master_CallFuncVec2Callback func(func_ cross_call_master.FuncVec2) plugify.Vector2
var Cross_call_master_CallFuncVec2Callback = &cross_call_master_CallFuncVec2Callback

//go:linkname cross_call_master_CallFuncVec3Callback cross_call_worker/cross_call_master._CallFuncVec3Callback
var cross_call_master_CallFuncVec3Callback func(func_ cross_call_master.FuncVec3) plugify.Vector3
var Cross_call_master_CallFuncVec3Callback = &cross_call_master_CallFuncVec3Callback

//go:linkname cross_call_master_CallFuncVec4Callback cross_call_worker/cross_call_master._CallFuncVec4Callback
var cross_call_master_CallFuncVec4Callback func(func_ cross_call_master.FuncVec4) plugify.Vector4
var Cross_call_master_CallFuncVec4Callback = &cross_call_master_CallFuncVec4Callback

//go:linkname cross_call_master_CallFuncMat4x4Callback cross_call_worker/cross_call_master._CallFuncMat4x4Callback
var cross_call_master_CallFuncMat4x4Callback func(func_ cross_call_master.FuncMat4x4) plugify.Matrix4x4
var Cross_call_master_CallFuncMat4x4Callback = &cross_call_master_CallFuncMat4x4Callback

//go:linkname cross_call_master_CallFuncAliasBoolCallback cross_call_worker/cross_call_master._CallFuncAliasBoolCallback
var cross_call_master_CallFuncAliasBoolCallback func(func_ cross_call_master.FuncAliasBool) cross_call_master.AliasBool
var Cross_call_master_CallFuncAliasBoolCallback = &cross_call_master_CallFuncAliasBoolCallback

//go:linkname cross_call_master_CallFuncAliasChar8Callback cross_call_worker/cross_call_master._CallFuncAliasChar8Callback
var cross_call_master_CallFuncAliasChar8Callback func(func_ cross_call_master.FuncAliasChar8) cross_call_master.AliasChar8
var Cross_call_master_CallFuncAliasChar8Callback = &cross_call_master_CallFuncAliasChar8Callback

//go:linkname cross_call_master_CallFuncAliasChar16Callback cross_call_worker/cross_call_master._CallFuncAliasChar16Callback
var cross_call_master_CallFuncAliasChar16Callback func(func_ cross_call_master.FuncAliasChar16) cross_call_master.AliasChar16
var Cross_call_master_CallFuncAliasChar16Callback = &cross_call_master_CallFuncAliasChar16Callback

//go:linkname cross_call_master_CallFuncAliasInt8Callback cross_call_worker/cross_call_master._CallFuncAliasInt8Callback
var cross_call_master_CallFuncAliasInt8Callback func(func_ cross_call_master.FuncAliasInt8) cross_call_master.AliasInt8
var Cross_call_master_CallFuncAliasInt8Callback = &cross_call_master_CallFuncAliasInt8Callback

//go:linkname cross_call_master_CallFuncAliasInt16Callback cross_call_worker/cross_call_master._CallFuncAliasInt16Callback
var cross_call_master_CallFuncAliasInt16Callback func(func_ cross_call_master.FuncAliasInt16) cross_call_master.AliasInt16
var Cross_call_master_CallFuncAliasInt16Callback = &cross_call_master_CallFuncAliasInt16Callback

//go:linkname cross_call_master_CallFuncAliasInt32Callback cross_call_worker/cross_call_master._CallFuncAliasInt32Callback
var cross_call_master_CallFuncAliasInt32Callback func(func_ cross_call_master.FuncAliasInt32) cross_call_master.AliasInt32
var Cross_call_master_CallFuncAliasInt32Callback = &cross_call_master_CallFuncAliasInt32Callback

//go:linkname cross_call_master_CallFuncAliasInt64Callback cross_call_worker/cross_call_master._CallFuncAliasInt64Callback
var cross_call_master_CallFuncAliasInt64Callback func(func_ cross_call_master.FuncAliasInt64) cross_call_master.AliasInt64
var Cross_call_master_CallFuncAliasInt64Callback = &cross_call_master_CallFuncAliasInt64Callback

//go:linkname cross_call_master_CallFuncAliasUInt8Callback cross_call_worker/cross_call_master._CallFuncAliasUInt8Callback
var cross_call_master_CallFuncAliasUInt8Callback func(func_ cross_call_master.FuncAliasUInt8) cross_call_master.AliasUInt8
var Cross_call_master_CallFuncAliasUInt8Callback = &cross_call_master_CallFuncAliasUInt8Callback

//go:linkname cross_call_master_CallFuncAliasUInt16Callback cross_call_worker/cross_call_master._CallFuncAliasUInt16Callback
var cross_call_master_CallFuncAliasUInt16Callback func(func_ cross_call_master.FuncAliasUInt16) cross_call_master.AliasUInt16
var Cross_call_master_CallFuncAliasUInt16Callback = &cross_call_master_CallFuncAliasUInt16Callback

//go:linkname cross_call_master_CallFuncAliasUInt32Callback cross_call_worker/cross_call_master._CallFuncAliasUInt32Callback
var cross_call_master_CallFuncAliasUInt32Callback func(func_ cross_call_master.FuncAliasUInt32) cross_call_master.AliasUInt32
var Cross_call_master_CallFuncAliasUInt32Callback = &cross_call_master_CallFuncAliasUInt32Callback

//go:linkname cross_call_master_CallFuncAliasUInt64Callback cross_call_worker/cross_call_master._CallFuncAliasUInt64Callback
var cross_call_master_CallFuncAliasUInt64Callback func(func_ cross_call_master.FuncAliasUInt64) cross_call_master.AliasUInt64
var Cross_call_master_CallFuncAliasUInt64Callback = &cross_call_master_CallFuncAliasUInt64Callback

//go:linkname cross_call_master_CallFuncAliasPtrCallback cross_call_worker/cross_call_master._CallFuncAliasPtrCallback
var cross_call_master_CallFuncAliasPtrCallback func(func_ cross_call_master.FuncAliasPtr) cross_call_master.AliasPtr
var Cross_call_master_CallFuncAliasPtrCallback = &cross_call_master_CallFuncAliasPtrCallback

//go:linkname cross_call_master_CallFuncAliasFloatCallback cross_call_worker/cross_call_master._CallFuncAliasFloatCallback
var cross_call_master_CallFuncAliasFloatCallback func(func_ cross_call_master.FuncAliasFloat) cross_call_master.AliasFloat
var Cross_call_master_CallFuncAliasFloatCallback = &cross_call_master_CallFuncAliasFloatCallback

//go:linkname cross_call_master_CallFuncAliasDoubleCallback cross_call_worker/cross_call_master._CallFuncAliasDoubleCallback
var cross_call_master_CallFuncAliasDoubleCallback func(func_ cross_call_master.FuncAliasDouble) cross_call_master.AliasDouble
var Cross_call_master_CallFuncAliasDoubleCallback = &cross_call_master_CallFuncAliasDoubleCallback

//go:linkname cross_call_master_CallFuncAliasStringCallback cross_call_worker/cross_call_master._CallFuncAliasStringCallback
var cross_call_master_CallFuncAliasStringCallback func(func_ cross_call_master.FuncAliasString) cross_call_master.AliasString
var Cross_call_master_CallFuncAliasStringCallback = &cross_call_master_CallFuncAliasStringCallback

//go:linkname cross_call_master_CallFuncAliasAnyCallback cross_call_worker/cross_call_master._CallFuncAliasAnyCallback
var cross_call_master_CallFuncAliasAnyCallback func(func_ cross_call_master.FuncAliasAny) cross_call_master.AliasAny
var Cross_call_master_CallFuncAliasAnyCallback = &cross_call_master_CallFuncAliasAnyCallback

//go:linkname cross_call_master_CallFuncAliasFunctionCallback cross_call_worker/cross_call_master._CallFuncAliasFunctionCallback
var cross_call_master_CallFuncAliasFunctionCallback func(func_ cross_call_master.FuncAliasFunction) cross_call_master.AliasFunction
var Cross_call_master_CallFuncAliasFunctionCallback = &cross_call_master_CallFuncAliasFunctionCallback

//go:linkname cross_call_master_CallFuncAliasBoolVectorCallback cross_call_worker/cross_call_master._CallFuncAliasBoolVectorCallback
var cross_call_master_CallFuncAliasBoolVectorCallback func(func_ cross_call_master.FuncAliasBoolVector) cross_call_master.AliasBoolVector
var Cross_call_master_CallFuncAliasBoolVectorCallback = &cross_call_master_CallFuncAliasBoolVectorCallback

//go:linkname cross_call_master_CallFuncAliasChar8VectorCallback cross_call_worker/cross_call_master._CallFuncAliasChar8VectorCallback
var cross_call_master_CallFuncAliasChar8VectorCallback func(func_ cross_call_master.FuncAliasChar8Vector) cross_call_master.AliasChar8Vector
var Cross_call_master_CallFuncAliasChar8VectorCallback = &cross_call_master_CallFuncAliasChar8VectorCallback

//go:linkname cross_call_master_CallFuncAliasChar16VectorCallback cross_call_worker/cross_call_master._CallFuncAliasChar16VectorCallback
var cross_call_master_CallFuncAliasChar16VectorCallback func(func_ cross_call_master.FuncAliasChar16Vector) cross_call_master.AliasChar16Vector
var Cross_call_master_CallFuncAliasChar16VectorCallback = &cross_call_master_CallFuncAliasChar16VectorCallback

//go:linkname cross_call_master_CallFuncAliasInt8VectorCallback cross_call_worker/cross_call_master._CallFuncAliasInt8VectorCallback
var cross_call_master_CallFuncAliasInt8VectorCallback func(func_ cross_call_master.FuncAliasInt8Vector) cross_call_master.AliasInt8Vector
var Cross_call_master_CallFuncAliasInt8VectorCallback = &cross_call_master_CallFuncAliasInt8VectorCallback

//go:linkname cross_call_master_CallFuncAliasInt16VectorCallback cross_call_worker/cross_call_master._CallFuncAliasInt16VectorCallback
var cross_call_master_CallFuncAliasInt16VectorCallback func(func_ cross_call_master.FuncAliasInt16Vector) cross_call_master.AliasInt16Vector
var Cross_call_master_CallFuncAliasInt16VectorCallback = &cross_call_master_CallFuncAliasInt16VectorCallback

//go:linkname cross_call_master_CallFuncAliasInt32VectorCallback cross_call_worker/cross_call_master._CallFuncAliasInt32VectorCallback
var cross_call_master_CallFuncAliasInt32VectorCallback func(func_ cross_call_master.FuncAliasInt32Vector) cross_call_master.AliasInt32Vector
var Cross_call_master_CallFuncAliasInt32VectorCallback = &cross_call_master_CallFuncAliasInt32VectorCallback

//go:linkname cross_call_master_CallFuncAliasInt64VectorCallback cross_call_worker/cross_call_master._CallFuncAliasInt64VectorCallback
var cross_call_master_CallFuncAliasInt64VectorCallback func(func_ cross_call_master.FuncAliasInt64Vector) cross_call_master.AliasInt64Vector
var Cross_call_master_CallFuncAliasInt64VectorCallback = &cross_call_master_CallFuncAliasInt64VectorCallback

//go:linkname cross_call_master_CallFuncAliasUInt8VectorCallback cross_call_worker/cross_call_master._CallFuncAliasUInt8VectorCallback
var cross_call_master_CallFuncAliasUInt8VectorCallback func(func_ cross_call_master.FuncAliasUInt8Vector) cross_call_master.AliasUInt8Vector
var Cross_call_master_CallFuncAliasUInt8VectorCallback = &cross_call_master_CallFuncAliasUInt8VectorCallback

//go:linkname cross_call_master_CallFuncAliasUInt16VectorCallback cross_call_worker/cross_call_master._CallFuncAliasUInt16VectorCallback
var cross_call_master_CallFuncAliasUInt16VectorCallback func(func_ cross_call_master.FuncAliasUInt16Vector) cross_call_master.AliasUInt16Vector
var Cross_call_master_CallFuncAliasUInt16VectorCallback = &cross_call_master_CallFuncAliasUInt16VectorCallback

//go:linkname cross_call_master_CallFuncAliasUInt32VectorCallback cross_call_worker/cross_call_master._CallFuncAliasUInt32VectorCallback
var cross_call_master_CallFuncAliasUInt32VectorCallback func(func_ cross_call_master.FuncAliasUInt32Vector) cross_call_master.AliasUInt32Vector
var Cross_call_master_CallFuncAliasUInt32VectorCallback = &cross_call_master_CallFuncAliasUInt32VectorCallback

//go:linkname cross_call_master_CallFuncAliasUInt64VectorCallback cross_call_worker/cross_call_master._CallFuncAliasUInt64VectorCallback
var cross_call_master_CallFuncAliasUInt64VectorCallback func(func_ cross_call_master.FuncAliasUInt64Vector) cross_call_master.AliasUInt64Vector
var Cross_call_master_CallFuncAliasUInt64VectorCallback = &cross_call_master_CallFuncAliasUInt64VectorCallback

//go:linkname cross_call_master_CallFuncAliasPtrVectorCallback cross_call_worker/cross_call_master._CallFuncAliasPtrVectorCallback
var cross_call_master_CallFuncAliasPtrVectorCallback func(func_ cross_call_master.FuncAliasPtrVector) cross_call_master.AliasPtrVector
var Cross_call_master_CallFuncAliasPtrVectorCallback = &cross_call_master_CallFuncAliasPtrVectorCallback

//go:linkname cross_call_master_CallFuncAliasFloatVectorCallback cross_call_worker/cross_call_master._CallFuncAliasFloatVectorCallback
var cross_call_master_CallFuncAliasFloatVectorCallback func(func_ cross_call_master.FuncAliasFloatVector) cross_call_master.AliasFloatVector
var Cross_call_master_CallFuncAliasFloatVectorCallback = &cross_call_master_CallFuncAliasFloatVectorCallback

//go:linkname cross_call_master_CallFuncAliasDoubleVectorCallback cross_call_worker/cross_call_master._CallFuncAliasDoubleVectorCallback
var cross_call_master_CallFuncAliasDoubleVectorCallback func(func_ cross_call_master.FuncAliasDoubleVector) cross_call_master.AliasDoubleVector
var Cross_call_master_CallFuncAliasDoubleVectorCallback = &cross_call_master_CallFuncAliasDoubleVectorCallback

//go:linkname cross_call_master_CallFuncAliasStringVectorCallback cross_call_worker/cross_call_master._CallFuncAliasStringVectorCallback
var cross_call_master_CallFuncAliasStringVectorCallback func(func_ cross_call_master.FuncAliasStringVector) cross_call_master.AliasStringVector
var Cross_call_master_CallFuncAliasStringVectorCallback = &cross_call_master_CallFuncAliasStringVectorCallback

//go:linkname cross_call_master_CallFuncAliasAnyVectorCallback cross_call_worker/cross_call_master._CallFuncAliasAnyVectorCallback
var cross_call_master_CallFuncAliasAnyVectorCallback func(func_ cross_call_master.FuncAliasAnyVector) cross_call_master.AliasAnyVector
var Cross_call_master_CallFuncAliasAnyVectorCallback = &cross_call_master_CallFuncAliasAnyVectorCallback

//go:linkname cross_call_master_CallFuncAliasVec2VectorCallback cross_call_worker/cross_call_master._CallFuncAliasVec2VectorCallback
var cross_call_master_CallFuncAliasVec2VectorCallback func(func_ cross_call_master.FuncAliasVec2Vector) cross_call_master.AliasVec2Vector
var Cross_call_master_CallFuncAliasVec2VectorCallback = &cross_call_master_CallFuncAliasVec2VectorCallback

//go:linkname cross_call_master_CallFuncAliasVec3VectorCallback cross_call_worker/cross_call_master._CallFuncAliasVec3VectorCallback
var cross_call_master_CallFuncAliasVec3VectorCallback func(func_ cross_call_master.FuncAliasVec3Vector) cross_call_master.AliasVec3Vector
var Cross_call_master_CallFuncAliasVec3VectorCallback = &cross_call_master_CallFuncAliasVec3VectorCallback

//go:linkname cross_call_master_CallFuncAliasVec4VectorCallback cross_call_worker/cross_call_master._CallFuncAliasVec4VectorCallback
var cross_call_master_CallFuncAliasVec4VectorCallback func(func_ cross_call_master.FuncAliasVec4Vector) cross_call_master.AliasVec4Vector
var Cross_call_master_CallFuncAliasVec4VectorCallback = &cross_call_master_CallFuncAliasVec4VectorCallback

//go:linkname cross_call_master_CallFuncAliasMat4x4VectorCallback cross_call_worker/cross_call_master._CallFuncAliasMat4x4VectorCallback
var cross_call_master_CallFuncAliasMat4x4VectorCallback func(func_ cross_call_master.FuncAliasMat4x4Vector) cross_call_master.AliasMat4x4Vector
var Cross_call_master_CallFuncAliasMat4x4VectorCallback = &cross_call_master_CallFuncAliasMat4x4VectorCallback

//go:linkname cross_call_master_CallFuncAliasVec2Callback cross_call_worker/cross_call_master._CallFuncAliasVec2Callback
var cross_call_master_CallFuncAliasVec2Callback func(func_ cross_call_master.FuncAliasVec2) cross_call_master.AliasVec2
var Cross_call_master_CallFuncAliasVec2Callback = &cross_call_master_CallFuncAliasVec2Callback

//go:linkname cross_call_master_CallFuncAliasVec3Callback cross_call_worker/cross_call_master._CallFuncAliasVec3Callback
var cross_call_master_CallFuncAliasVec3Callback func(func_ cross_call_master.FuncAliasVec3) cross_call_master.AliasVec3
var Cross_call_master_CallFuncAliasVec3Callback = &cross_call_master_CallFuncAliasVec3Callback

//go:linkname cross_call_master_CallFuncAliasVec4Callback cross_call_worker/cross_call_master._CallFuncAliasVec4Callback
var cross_call_master_CallFuncAliasVec4Callback func(func_ cross_call_master.FuncAliasVec4) cross_call_master.AliasVec4
var Cross_call_master_CallFuncAliasVec4Callback = &cross_call_master_CallFuncAliasVec4Callback

//go:linkname cross_call_master_CallFuncAliasMat4x4Callback cross_call_worker/cross_call_master._CallFuncAliasMat4x4Callback
var cross_call_master_CallFuncAliasMat4x4Callback func(func_ cross_call_master.FuncAliasMat4x4) cross_call_master.AliasMat4x4
var Cross_call_master_CallFuncAliasMat4x4Callback = &cross_call_master_CallFuncAliasMat4x4Callback

//go:linkname cross_call_master_CallFuncAliasAllCallback cross_call_worker/cross_call_master._CallFuncAliasAllCallback
var cross_call_master_CallFuncAliasAllCallback func(func_ cross_call_master.FuncAliasAll) cross_call_master.AliasString
var Cross_call_master_CallFuncAliasAllCallback = &cross_call_master_CallFuncAliasAllCallback

//go:linkname cross_call_master_CallFunc1Callback cross_call_worker/cross_call_master._CallFunc1Callback
var cross_call_master_CallFunc1Callback func(func_ cross_call_master.Func1) int32
var Cross_call_master_CallFunc1Callback = &cross_call_master_CallFunc1Callback

//go:linkname cross_call_master_CallFunc2Callback cross_call_worker/cross_call_master._CallFunc2Callback
var cross_call_master_CallFunc2Callback func(func_ cross_call_master.Func2) int8
var Cross_call_master_CallFunc2Callback = &cross_call_master_CallFunc2Callback

//go:linkname cross_call_master_CallFunc3Callback cross_call_worker/cross_call_master._CallFunc3Callback
var cross_call_master_CallFunc3Callback func(func_ cross_call_master.Func3)
var Cross_call_master_CallFunc3Callback = &cross_call_master_CallFunc3Callback

//go:linkname cross_call_master_CallFunc4Callback cross_call_worker/cross_call_master._CallFunc4Callback
var cross_call_master_CallFunc4Callback func(func_ cross_call_master.Func4) plugify.Vector4
var Cross_call_master_CallFunc4Callback = &cross_call_master_CallFunc4Callback

//go:linkname cross_call_master_CallFunc5Callback cross_call_worker/cross_call_master._CallFunc5Callback
var cross_call_master_CallFunc5Callback func(func_ cross_call_master.Func5) bool
var Cross_call_master_CallFunc5Callback = &cross_call_master_CallFunc5Callback

//go:linkname cross_call_master_CallFunc6Callback cross_call_worker/cross_call_master._CallFunc6Callback
var cross_call_master_CallFunc6Callback func(func_ cross_call_master.Func6) int64
var Cross_call_master_CallFunc6Callback = &cross_call_master_CallFunc6Callback

//go:linkname cross_call_master_CallFunc7Callback cross_call_worker/cross_call_master._CallFunc7Callback
var cross_call_master_CallFunc7Callback func(func_ cross_call_master.Func7) float64
var Cross_call_master_CallFunc7Callback = &cross_call_master_CallFunc7Callback

//go:linkname cross_call_master_CallFunc8Callback cross_call_worker/cross_call_master._CallFunc8Callback
var cross_call_master_CallFunc8Callback func(func_ cross_call_master.Func8) plugify.Matrix4x4
var Cross_call_master_CallFunc8Callback = &cross_call_master_CallFunc8Callback

//go:linkname cross_call_master_CallFunc9Callback cross_call_worker/cross_call_master._CallFunc9Callback
var cross_call_master_CallFunc9Callback func(func_ cross_call_master.Func9)
var Cross_call_master_CallFunc9Callback = &cross_call_master_CallFunc9Callback

//go:linkname cross_call_master_CallFunc10Callback cross_call_worker/cross_call_master._CallFunc10Callback
var cross_call_master_CallFunc10Callback func(func_ cross_call_master.Func10) uint32
var Cross_call_master_CallFunc10Callback = &cross_call_master_CallFunc10Callback

//go:linkname cross_call_master_CallFunc11Callback cross_call_worker/cross_call_master._CallFunc11Callback
var cross_call_master_CallFunc11Callback func(func_ cross_call_master.Func11) uintptr
var Cross_call_master_CallFunc11Callback = &cross_call_master_CallFunc11Callback

//go:linkname cross_call_master_CallFunc12Callback cross_call_worker/cross_call_master._CallFunc12Callback
var cross_call_master_CallFunc12Callback func(func_ cross_call_master.Func12) bool
var Cross_call_master_CallFunc12Callback = &cross_call_master_CallFunc12Callback

//go:linkname cross_call_master_CallFunc13Callback cross_call_worker/cross_call_master._CallFunc13Callback
var cross_call_master_CallFunc13Callback func(func_ cross_call_master.Func13) string
var Cross_call_master_CallFunc13Callback = &cross_call_master_CallFunc13Callback

//go:linkname cross_call_master_CallFunc14Callback cross_call_worker/cross_call_master._CallFunc14Callback
var cross_call_master_CallFunc14Callback func(func_ cross_call_master.Func14) []string
var Cross_call_master_CallFunc14Callback = &cross_call_master_CallFunc14Callback

//go:linkname cross_call_master_CallFunc15Callback cross_call_worker/cross_call_master._CallFunc15Callback
var cross_call_master_CallFunc15Callback func(func_ cross_call_master.Func15) int16
var Cross_call_master_CallFunc15Callback = &cross_call_master_CallFunc15Callback

//go:linkname cross_call_master_CallFunc16Callback cross_call_worker/cross_call_master._CallFunc16Callback
var cross_call_master_CallFunc16Callback func(func_ cross_call_master.Func16) uintptr
var Cross_call_master_CallFunc16Callback = &cross_call_master_CallFunc16Callback

//go:linkname cross_call_master_CallFunc17Callback cross_call_worker/cross_call_master._CallFunc17Callback
var cross_call_master_CallFunc17Callback func(func_ cross_call_master.Func17) string
var Cross_call_master_CallFunc17Callback = &cross_call_master_CallFunc17Callback

//go:linkname cross_call_master_CallFunc18Callback cross_call_worker/cross_call_master._CallFunc18Callback
var cross_call_master_CallFunc18Callback func(func_ cross_call_master.Func18) string
var Cross_call_master_CallFunc18Callback = &cross_call_master_CallFunc18Callback

//go:linkname cross_call_master_CallFunc19Callback cross_call_worker/cross_call_master._CallFunc19Callback
var cross_call_master_CallFunc19Callback func(func_ cross_call_master.Func19) string
var Cross_call_master_CallFunc19Callback = &cross_call_master_CallFunc19Callback

//go:linkname cross_call_master_CallFunc20Callback cross_call_worker/cross_call_master._CallFunc20Callback
var cross_call_master_CallFunc20Callback func(func_ cross_call_master.Func20) string
var Cross_call_master_CallFunc20Callback = &cross_call_master_CallFunc20Callback

//go:linkname cross_call_master_CallFunc21Callback cross_call_worker/cross_call_master._CallFunc21Callback
var cross_call_master_CallFunc21Callback func(func_ cross_call_master.Func21) string
var Cross_call_master_CallFunc21Callback = &cross_call_master_CallFunc21Callback

//go:linkname cross_call_master_CallFunc22Callback cross_call_worker/cross_call_master._CallFunc22Callback
var cross_call_master_CallFunc22Callback func(func_ cross_call_master.Func22) string
var Cross_call_master_CallFunc22Callback = &cross_call_master_CallFunc22Callback

//go:linkname cross_call_master_CallFunc23Callback cross_call_worker/cross_call_master._CallFunc23Callback
var cross_call_master_CallFunc23Callback func(func_ cross_call_master.Func23) string
var Cross_call_master_CallFunc23Callback = &cross_call_master_CallFunc23Callback

//go:linkname cross_call_master_CallFunc24Callback cross_call_worker/cross_call_master._CallFunc24Callback
var cross_call_master_CallFunc24Callback func(func_ cross_call_master.Func24) string
var Cross_call_master_CallFunc24Callback = &cross_call_master_CallFunc24Callback

//go:linkname cross_call_master_CallFunc25Callback cross_call_worker/cross_call_master._CallFunc25Callback
var cross_call_master_CallFunc25Callback func(func_ cross_call_master.Func25) string
var Cross_call_master_CallFunc25Callback = &cross_call_master_CallFunc25Callback

//go:linkname cross_call_master_CallFunc26Callback cross_call_worker/cross_call_master._CallFunc26Callback
var cross_call_master_CallFunc26Callback func(func_ cross_call_master.Func26) string
var Cross_call_master_CallFunc26Callback = &cross_call_master_CallFunc26Callback

//go:linkname cross_call_master_CallFunc27Callback cross_call_worker/cross_call_master._CallFunc27Callback
var cross_call_master_CallFunc27Callback func(func_ cross_call_master.Func27) string
var Cross_call_master_CallFunc27Callback = &cross_call_master_CallFunc27Callback

//go:linkname cross_call_master_CallFunc28Callback cross_call_worker/cross_call_master._CallFunc28Callback
var cross_call_master_CallFunc28Callback func(func_ cross_call_master.Func28) string
var Cross_call_master_CallFunc28Callback = &cross_call_master_CallFunc28Callback

//go:linkname cross_call_master_CallFunc29Callback cross_call_worker/cross_call_master._CallFunc29Callback
var cross_call_master_CallFunc29Callback func(func_ cross_call_master.Func29) string
var Cross_call_master_CallFunc29Callback = &cross_call_master_CallFunc29Callback

//go:linkname cross_call_master_CallFunc30Callback cross_call_worker/cross_call_master._CallFunc30Callback
var cross_call_master_CallFunc30Callback func(func_ cross_call_master.Func30) string
var Cross_call_master_CallFunc30Callback = &cross_call_master_CallFunc30Callback

//go:linkname cross_call_master_CallFunc31Callback cross_call_worker/cross_call_master._CallFunc31Callback
var cross_call_master_CallFunc31Callback func(func_ cross_call_master.Func31) string
var Cross_call_master_CallFunc31Callback = &cross_call_master_CallFunc31Callback

//go:linkname cross_call_master_CallFunc32Callback cross_call_worker/cross_call_master._CallFunc32Callback
var cross_call_master_CallFunc32Callback func(func_ cross_call_master.Func32) string
var Cross_call_master_CallFunc32Callback = &cross_call_master_CallFunc32Callback

//go:linkname cross_call_master_CallFunc33Callback cross_call_worker/cross_call_master._CallFunc33Callback
var cross_call_master_CallFunc33Callback func(func_ cross_call_master.Func33) string
var Cross_call_master_CallFunc33Callback = &cross_call_master_CallFunc33Callback

//go:linkname cross_call_master_CallFuncEnumCallback cross_call_worker/cross_call_master._CallFuncEnumCallback
var cross_call_master_CallFuncEnumCallback func(func_ cross_call_master.FuncEnum) string
var Cross_call_master_CallFuncEnumCallback = &cross_call_master_CallFuncEnumCallback

//go:linkname cross_call_master_ResourceHandleCreate cross_call_worker/cross_call_master._ResourceHandleCreate
var cross_call_master_ResourceHandleCreate func(id int32, name string) uintptr
var Cross_call_master_ResourceHandleCreate = &cross_call_master_ResourceHandleCreate

//go:linkname cross_call_master_ResourceHandleCreateDefault cross_call_worker/cross_call_master._ResourceHandleCreateDefault
var cross_call_master_ResourceHandleCreateDefault func() uintptr
var Cross_call_master_ResourceHandleCreateDefault = &cross_call_master_ResourceHandleCreateDefault

//go:linkname cross_call_master_ResourceHandleDestroy cross_call_worker/cross_call_master._ResourceHandleDestroy
var cross_call_master_ResourceHandleDestroy func(handle uintptr)
var Cross_call_master_ResourceHandleDestroy = &cross_call_master_ResourceHandleDestroy

//go:linkname cross_call_master_ResourceHandleGetId cross_call_worker/cross_call_master._ResourceHandleGetId
var cross_call_master_ResourceHandleGetId func(handle uintptr) int32
var Cross_call_master_ResourceHandleGetId = &cross_call_master_ResourceHandleGetId

//go:linkname cross_call_master_ResourceHandleGetName cross_call_worker/cross_call_master._ResourceHandleGetName
var cross_call_master_ResourceHandleGetName func(handle uintptr) string
var Cross_call_master_ResourceHandleGetName = &cross_call_master_ResourceHandleGetName

//go:linkname cross_call_master_ResourceHandleSetName cross_call_worker/cross_call_master._ResourceHandleSetName
var cross_call_master_ResourceHandleSetName func(handle uintptr, name string)
var Cross_call_master_ResourceHandleSetName = &cross_call_master_ResourceHandleSetName

//go:linkname cross_call_master_ResourceHandleIncrementCounter cross_call_worker/cross_call_master._ResourceHandleIncrementCounter
var cross_call_master_ResourceHandleIncrementCounter func(handle uintptr)
var Cross_call_master_ResourceHandleIncrementCounter = &cross_call_master_ResourceHandleIncrementCounter

//go:linkname cross_call_master_ResourceHandleGetCounter cross_call_worker/cross_call_master._ResourceHandleGetCounter
var cross_call_master_ResourceHandleGetCounter func(handle uintptr) int32
var Cross_call_master_ResourceHandleGetCounter = &cross_call_master_ResourceHandleGetCounter

//go:linkname cross_call_master_ResourceHandleAddData cross_call_worker/cross_call_master._ResourceHandleAddData
var cross_call_master_ResourceHandleAddData func(handle uintptr, value float32)
var Cross_call_master_ResourceHandleAddData = &cross_call_master_ResourceHandleAddData

//go:linkname cross_call_master_ResourceHandleGetData cross_call_worker/cross_call_master._ResourceHandleGetData
var cross_call_master_ResourceHandleGetData func(handle uintptr) []float32
var Cross_call_master_ResourceHandleGetData = &cross_call_master_ResourceHandleGetData

//go:linkname cross_call_master_ResourceHandleGetAliveCount cross_call_worker/cross_call_master._ResourceHandleGetAliveCount
var cross_call_master_ResourceHandleGetAliveCount func() int32
var Cross_call_master_ResourceHandleGetAliveCount = &cross_call_master_ResourceHandleGetAliveCount

//go:linkname cross_call_master_ResourceHandleGetTotalCreated cross_call_worker/cross_call_master._ResourceHandleGetTotalCreated
var cross_call_master_ResourceHandleGetTotalCreated func() int32
var Cross_call_master_ResourceHandleGetTotalCreated = &cross_call_master_ResourceHandleGetTotalCreated

//go:linkname cross_call_master_ResourceHandleGetTotalDestroyed cross_call_worker/cross_call_master._ResourceHandleGetTotalDestroyed
var cross_call_master_ResourceHandleGetTotalDestroyed func() int32
var Cross_call_master_ResourceHandleGetTotalDestroyed = &cross_call_master_ResourceHandleGetTotalDestroyed

//go:linkname cross_call_master_CounterCreate cross_call_worker/cross_call_master._CounterCreate
var cross_call_master_CounterCreate func(initialValue int64) uintptr
var Cross_call_master_CounterCreate = &cross_call_master_CounterCreate

//go:linkname cross_call_master_CounterCreateZero cross_call_worker/cross_call_master._CounterCreateZero
var cross_call_master_CounterCreateZero func() uintptr
var Cross_call_master_CounterCreateZero = &cross_call_master_CounterCreateZero

//go:linkname cross_call_master_CounterGetValue cross_call_worker/cross_call_master._CounterGetValue
var cross_call_master_CounterGetValue func(counter uintptr) int64
var Cross_call_master_CounterGetValue = &cross_call_master_CounterGetValue

//go:linkname cross_call_master_CounterSetValue cross_call_worker/cross_call_master._CounterSetValue
var cross_call_master_CounterSetValue func(counter uintptr, value int64)
var Cross_call_master_CounterSetValue = &cross_call_master_CounterSetValue

//go:linkname cross_call_master_CounterIncrement cross_call_worker/cross_call_master._CounterIncrement
var cross_call_master_CounterIncrement func(counter uintptr)
var Cross_call_master_CounterIncrement = &cross_call_master_CounterIncrement

//go:linkname cross_call_master_CounterDecrement cross_call_worker/cross_call_master._CounterDecrement
var cross_call_master_CounterDecrement func(counter uintptr)
var Cross_call_master_CounterDecrement = &cross_call_master_CounterDecrement

//go:linkname cross_call_master_CounterAdd cross_call_worker/cross_call_master._CounterAdd
var cross_call_master_CounterAdd func(counter uintptr, amount int64)
var Cross_call_master_CounterAdd = &cross_call_master_CounterAdd

//go:linkname cross_call_master_CounterReset cross_call_worker/cross_call_master._CounterReset
var cross_call_master_CounterReset func(counter uintptr)
var Cross_call_master_CounterReset = &cross_call_master_CounterReset

//go:linkname cross_call_master_CounterIsPositive cross_call_worker/cross_call_master._CounterIsPositive
var cross_call_master_CounterIsPositive func(counter uintptr) bool
var Cross_call_master_CounterIsPositive = &cross_call_master_CounterIsPositive

//go:linkname cross_call_master_CounterCompare cross_call_worker/cross_call_master._CounterCompare
var cross_call_master_CounterCompare func(value1 int64, value2 int64) int32
var Cross_call_master_CounterCompare = &cross_call_master_CounterCompare

//go:linkname cross_call_master_CounterSum cross_call_worker/cross_call_master._CounterSum
var cross_call_master_CounterSum func(values []int64) int64
var Cross_call_master_CounterSum = &cross_call_master_CounterSum
