/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "autoexports.go"
 #include "autoexports.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void __NoParamReturnVoid(void);
extern __declspec(dllexport) GoUint8 __NoParamReturnBool(void);
extern __declspec(dllexport) GoInt8 __NoParamReturnChar8(void);
extern __declspec(dllexport) GoUint16 __NoParamReturnChar16(void);
extern __declspec(dllexport) GoInt8 __NoParamReturnInt8(void);
extern __declspec(dllexport) GoInt16 __NoParamReturnInt16(void);
extern __declspec(dllexport) GoInt32 __NoParamReturnInt32(void);
extern __declspec(dllexport) GoInt64 __NoParamReturnInt64(void);
extern __declspec(dllexport) GoUint8 __NoParamReturnUInt8(void);
extern __declspec(dllexport) GoUint16 __NoParamReturnUInt16(void);
extern __declspec(dllexport) GoUint32 __NoParamReturnUInt32(void);
extern __declspec(dllexport) GoUint64 __NoParamReturnUInt64(void);
extern __declspec(dllexport) GoUintptr __NoParamReturnPointer(void);
extern __declspec(dllexport) GoFloat32 __NoParamReturnFloat(void);
extern __declspec(dllexport) GoFloat64 __NoParamReturnDouble(void);
extern __declspec(dllexport) void* __NoParamReturnFunction(void);
extern __declspec(dllexport) String __NoParamReturnString(void);
extern __declspec(dllexport) Variant __NoParamReturnAny(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayBool(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayChar8(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayChar16(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayInt8(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayInt16(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayInt32(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayInt64(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt8(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt16(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt32(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayUInt64(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayPointer(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayFloat(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayDouble(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayString(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayAny(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayVector2(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayVector3(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayVector4(void);
extern __declspec(dllexport) Vector __NoParamReturnArrayMatrix4x4(void);
extern __declspec(dllexport) Vector2 __NoParamReturnVector2(void);
extern __declspec(dllexport) Vector3 __NoParamReturnVector3(void);
extern __declspec(dllexport) Vector4 __NoParamReturnVector4(void);
extern __declspec(dllexport) Matrix4x4 __NoParamReturnMatrix4x4(void);
extern __declspec(dllexport) void __Param1(GoInt32 a);
extern __declspec(dllexport) void __Param2(GoInt32 a, GoFloat32 b);
extern __declspec(dllexport) void __Param3(GoInt32 a, GoFloat32 b, GoFloat64 c);
extern __declspec(dllexport) void __Param4(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d);
extern __declspec(dllexport) void __Param5(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e);
extern __declspec(dllexport) void __Param6(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f);
extern __declspec(dllexport) void __Param7(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g);
extern __declspec(dllexport) void __Param8(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h);
extern __declspec(dllexport) void __Param9(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h, GoInt16 k);
extern __declspec(dllexport) void __Param10(GoInt32 a, GoFloat32 b, GoFloat64 c, Vector4* d, Vector* e, GoInt8 f, String* g, GoUint16 h, GoInt16 k, GoUintptr l);
extern __declspec(dllexport) void __ParamRef1(GoInt32* a);
extern __declspec(dllexport) void __ParamRef2(GoInt32* a, GoFloat32* b);
extern __declspec(dllexport) void __ParamRef3(GoInt32* a, GoFloat32* b, GoFloat64* c);
extern __declspec(dllexport) void __ParamRef4(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d);
extern __declspec(dllexport) void __ParamRef5(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e);
extern __declspec(dllexport) void __ParamRef6(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f);
extern __declspec(dllexport) void __ParamRef7(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g);
extern __declspec(dllexport) void __ParamRef8(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h);
extern __declspec(dllexport) void __ParamRef9(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h, GoInt16* k);
extern __declspec(dllexport) void __ParamRef10(GoInt32* a, GoFloat32* b, GoFloat64* c, Vector4* d, Vector* e, GoInt8* f, String* g, GoUint16* h, GoInt16* k, GoUintptr* l);
extern __declspec(dllexport) void __ParamRefVectors(Vector* p1, Vector* p2, Vector* p3, Vector* p4, Vector* p5, Vector* p6, Vector* p7, Vector* p8, Vector* p9, Vector* p10, Vector* p11, Vector* p12, Vector* p13, Vector* p14, Vector* p15);
extern __declspec(dllexport) GoInt64 __ParamAllPrimitives(GoUint8 p1, GoInt8 p2, GoUint16 p3, GoInt8 p4, GoInt16 p5, GoInt32 p6, GoInt64 p7, GoUint8 p8, GoUint16 p9, GoUint32 p10, GoUint64 p11, GoUintptr p12, GoFloat32 p13, GoFloat64 p14);
extern __declspec(dllexport) GoInt32 __ParamEnum(GoInt32 p1, Vector* p2);
extern __declspec(dllexport) GoInt32 __ParamEnumRef(GoInt32* p1, Vector* p2);
extern __declspec(dllexport) void __ParamVariant(Variant* p1, Vector* p2);
extern __declspec(dllexport) void __ParamVariantRef(Variant* p1, Vector* p2);
extern __declspec(dllexport) void __CallFuncVoid(void* func_);
extern __declspec(dllexport) GoUint8 __CallFuncBool(void* func_);
extern __declspec(dllexport) GoInt8 __CallFuncChar8(void* func_);
extern __declspec(dllexport) GoUint16 __CallFuncChar16(void* func_);
extern __declspec(dllexport) GoInt8 __CallFuncInt8(void* func_);
extern __declspec(dllexport) GoInt16 __CallFuncInt16(void* func_);
extern __declspec(dllexport) GoInt32 __CallFuncInt32(void* func_);
extern __declspec(dllexport) GoInt64 __CallFuncInt64(void* func_);
extern __declspec(dllexport) GoUint8 __CallFuncUInt8(void* func_);
extern __declspec(dllexport) GoUint16 __CallFuncUInt16(void* func_);
extern __declspec(dllexport) GoUint32 __CallFuncUInt32(void* func_);
extern __declspec(dllexport) GoUint64 __CallFuncUInt64(void* func_);
extern __declspec(dllexport) GoUintptr __CallFuncPtr(void* func_);
extern __declspec(dllexport) GoFloat32 __CallFuncFloat(void* func_);
extern __declspec(dllexport) GoFloat64 __CallFuncDouble(void* func_);
extern __declspec(dllexport) GoUintptr __CallFuncFunction(void* func_);
extern __declspec(dllexport) String __CallFuncString(void* func_);
extern __declspec(dllexport) Variant __CallFuncAny(void* func_);
extern __declspec(dllexport) Vector __CallFuncBoolVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncChar8Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncChar16Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt8Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt16Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt32Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncInt64Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt8Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt16Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt32Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncUInt64Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncPtrVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncFloatVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncDoubleVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncStringVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncAnyVector(void* func_);
extern __declspec(dllexport) Vector __CallFuncVec2Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncVec3Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncVec4Vector(void* func_);
extern __declspec(dllexport) Vector __CallFuncMat4x4Vector(void* func_);
extern __declspec(dllexport) Vector2 __CallFuncVec2(void* func_);
extern __declspec(dllexport) Vector3 __CallFuncVec3(void* func_);
extern __declspec(dllexport) Vector4 __CallFuncVec4(void* func_);
extern __declspec(dllexport) Matrix4x4 __CallFuncMat4x4(void* func_);
extern __declspec(dllexport) GoInt32 __CallFunc1(void* func_);
extern __declspec(dllexport) GoInt8 __CallFunc2(void* func_);
extern __declspec(dllexport) void __CallFunc3(void* func_);
extern __declspec(dllexport) Vector4 __CallFunc4(void* func_);
extern __declspec(dllexport) GoUint8 __CallFunc5(void* func_);
extern __declspec(dllexport) GoInt64 __CallFunc6(void* func_);
extern __declspec(dllexport) GoFloat64 __CallFunc7(void* func_);
extern __declspec(dllexport) Matrix4x4 __CallFunc8(void* func_);
extern __declspec(dllexport) void __CallFunc9(void* func_);
extern __declspec(dllexport) GoUint32 __CallFunc10(void* func_);
extern __declspec(dllexport) GoUintptr __CallFunc11(void* func_);
extern __declspec(dllexport) GoUint8 __CallFunc12(void* func_);
extern __declspec(dllexport) String __CallFunc13(void* func_);
extern __declspec(dllexport) Vector __CallFunc14(void* func_);
extern __declspec(dllexport) GoInt16 __CallFunc15(void* func_);
extern __declspec(dllexport) GoUintptr __CallFunc16(void* func_);
extern __declspec(dllexport) String __CallFunc17(void* func_);
extern __declspec(dllexport) String __CallFunc18(void* func_);
extern __declspec(dllexport) String __CallFunc19(void* func_);
extern __declspec(dllexport) String __CallFunc20(void* func_);
extern __declspec(dllexport) String __CallFunc21(void* func_);
extern __declspec(dllexport) String __CallFunc22(void* func_);
extern __declspec(dllexport) String __CallFunc23(void* func_);
extern __declspec(dllexport) String __CallFunc24(void* func_);
extern __declspec(dllexport) String __CallFunc25(void* func_);
extern __declspec(dllexport) String __CallFunc26(void* func_);
extern __declspec(dllexport) String __CallFunc27(void* func_);
extern __declspec(dllexport) String __CallFunc28(void* func_);
extern __declspec(dllexport) String __CallFunc29(void* func_);
extern __declspec(dllexport) String __CallFunc30(void* func_);
extern __declspec(dllexport) String __CallFunc31(void* func_);
extern __declspec(dllexport) String __CallFunc32(void* func_);
extern __declspec(dllexport) String __CallFunc33(void* func_);
extern __declspec(dllexport) String __CallFuncEnum(void* func_);
extern __declspec(dllexport) String __ReverseNoParamReturnVoid(void);
extern __declspec(dllexport) String __ReverseNoParamReturnBool(void);
extern __declspec(dllexport) String __ReverseNoParamReturnChar8(void);
extern __declspec(dllexport) String __ReverseNoParamReturnChar16(void);
extern __declspec(dllexport) String __ReverseNoParamReturnInt8(void);
extern __declspec(dllexport) String __ReverseNoParamReturnInt16(void);
extern __declspec(dllexport) String __ReverseNoParamReturnInt32(void);
extern __declspec(dllexport) String __ReverseNoParamReturnInt64(void);
extern __declspec(dllexport) String __ReverseNoParamReturnUInt8(void);
extern __declspec(dllexport) String __ReverseNoParamReturnUInt16(void);
extern __declspec(dllexport) String __ReverseNoParamReturnUInt32(void);
extern __declspec(dllexport) String __ReverseNoParamReturnUInt64(void);
extern __declspec(dllexport) String __ReverseNoParamReturnPointer(void);
extern __declspec(dllexport) String __ReverseNoParamReturnFloat(void);
extern __declspec(dllexport) String __ReverseNoParamReturnDouble(void);
extern __declspec(dllexport) String __ReverseNoParamReturnFunction(void);
extern __declspec(dllexport) String __ReverseNoParamReturnString(void);
extern __declspec(dllexport) String __ReverseNoParamReturnAny(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayBool(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayChar8(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayChar16(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayInt8(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayInt16(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayInt32(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayInt64(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayUInt8(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayUInt16(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayUInt32(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayUInt64(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayPointer(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayFloat(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayDouble(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayString(void);
extern __declspec(dllexport) String __ReverseNoParamReturnArrayAny(void);
extern __declspec(dllexport) String __ReverseNoParamReturnVector2(void);
extern __declspec(dllexport) String __ReverseNoParamReturnVector3(void);
extern __declspec(dllexport) String __ReverseNoParamReturnVector4(void);
extern __declspec(dllexport) String __ReverseNoParamReturnMatrix4x4(void);
extern __declspec(dllexport) String __ReverseParam1(void);
extern __declspec(dllexport) String __ReverseParam2(void);
extern __declspec(dllexport) String __ReverseParam3(void);
extern __declspec(dllexport) String __ReverseParam4(void);
extern __declspec(dllexport) String __ReverseParam5(void);
extern __declspec(dllexport) String __ReverseParam6(void);
extern __declspec(dllexport) String __ReverseParam7(void);
extern __declspec(dllexport) String __ReverseParam8(void);
extern __declspec(dllexport) String __ReverseParam9(void);
extern __declspec(dllexport) String __ReverseParam10(void);
extern __declspec(dllexport) String __ReverseParamRef1(void);
extern __declspec(dllexport) String __ReverseParamRef2(void);
extern __declspec(dllexport) String __ReverseParamRef3(void);
extern __declspec(dllexport) String __ReverseParamRef4(void);
extern __declspec(dllexport) String __ReverseParamRef5(void);
extern __declspec(dllexport) String __ReverseParamRef6(void);
extern __declspec(dllexport) String __ReverseParamRef7(void);
extern __declspec(dllexport) String __ReverseParamRef8(void);
extern __declspec(dllexport) String __ReverseParamRef9(void);
extern __declspec(dllexport) String __ReverseParamRef10(void);
extern __declspec(dllexport) String __ReverseParamRefVectors(void);
extern __declspec(dllexport) String __ReverseParamAllPrimitives(void);
extern __declspec(dllexport) String __ReverseParamEnum(void);
extern __declspec(dllexport) String __ReverseParamEnumRef(void);
extern __declspec(dllexport) String __ReverseParamVariant(void);
extern __declspec(dllexport) String __ReverseParamVariantRef(void);
extern __declspec(dllexport) String __ReverseCallFuncVoid(void);
extern __declspec(dllexport) String __ReverseCallFuncBool(void);
extern __declspec(dllexport) String __ReverseCallFuncChar8(void);
extern __declspec(dllexport) String __ReverseCallFuncChar16(void);
extern __declspec(dllexport) String __ReverseCallFuncInt8(void);
extern __declspec(dllexport) String __ReverseCallFuncInt16(void);
extern __declspec(dllexport) String __ReverseCallFuncInt32(void);
extern __declspec(dllexport) String __ReverseCallFuncInt64(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt8(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt16(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt32(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt64(void);
extern __declspec(dllexport) String __ReverseCallFuncPtr(void);
extern __declspec(dllexport) String __ReverseCallFuncFloat(void);
extern __declspec(dllexport) String __ReverseCallFuncDouble(void);
extern __declspec(dllexport) String __ReverseCallFuncString(void);
extern __declspec(dllexport) String __ReverseCallFuncAny(void);
extern __declspec(dllexport) String __ReverseCallFuncBoolVector(void);
extern __declspec(dllexport) String __ReverseCallFuncChar8Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncChar16Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncInt8Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncInt16Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncInt32Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncInt64Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt8Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt16Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt32Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncUInt64Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncPtrVector(void);
extern __declspec(dllexport) String __ReverseCallFuncFloatVector(void);
extern __declspec(dllexport) String __ReverseCallFuncDoubleVector(void);
extern __declspec(dllexport) String __ReverseCallFuncStringVector(void);
extern __declspec(dllexport) String __ReverseCallFuncAnyVector(void);
extern __declspec(dllexport) String __ReverseCallFuncVec2Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncVec3Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncVec4Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncMat4x4Vector(void);
extern __declspec(dllexport) String __ReverseCallFuncVec2(void);
extern __declspec(dllexport) String __ReverseCallFuncVec3(void);
extern __declspec(dllexport) String __ReverseCallFuncVec4(void);
extern __declspec(dllexport) String __ReverseCallFuncMat4x4(void);
extern __declspec(dllexport) String __ReverseCallFunc1(void);
extern __declspec(dllexport) String __ReverseCallFunc2(void);
extern __declspec(dllexport) String __ReverseCallFunc3(void);
extern __declspec(dllexport) String __ReverseCallFunc4(void);
extern __declspec(dllexport) String __ReverseCallFunc5(void);
extern __declspec(dllexport) String __ReverseCallFunc6(void);
extern __declspec(dllexport) String __ReverseCallFunc7(void);
extern __declspec(dllexport) String __ReverseCallFunc8(void);
extern __declspec(dllexport) String __ReverseCallFunc9(void);
extern __declspec(dllexport) String __ReverseCallFunc10(void);
extern __declspec(dllexport) String __ReverseCallFunc11(void);
extern __declspec(dllexport) String __ReverseCallFunc12(void);
extern __declspec(dllexport) String __ReverseCallFunc13(void);
extern __declspec(dllexport) String __ReverseCallFunc14(void);
extern __declspec(dllexport) String __ReverseCallFunc15(void);
extern __declspec(dllexport) String __ReverseCallFunc16(void);
extern __declspec(dllexport) String __ReverseCallFunc17(void);
extern __declspec(dllexport) String __ReverseCallFunc18(void);
extern __declspec(dllexport) String __ReverseCallFunc19(void);
extern __declspec(dllexport) String __ReverseCallFunc20(void);
extern __declspec(dllexport) String __ReverseCallFunc21(void);
extern __declspec(dllexport) String __ReverseCallFunc22(void);
extern __declspec(dllexport) String __ReverseCallFunc23(void);
extern __declspec(dllexport) String __ReverseCallFunc24(void);
extern __declspec(dllexport) String __ReverseCallFunc25(void);
extern __declspec(dllexport) String __ReverseCallFunc26(void);
extern __declspec(dllexport) String __ReverseCallFunc27(void);
extern __declspec(dllexport) String __ReverseCallFunc28(void);
extern __declspec(dllexport) String __ReverseCallFunc29(void);
extern __declspec(dllexport) String __ReverseCallFunc30(void);
extern __declspec(dllexport) String __ReverseCallFunc31(void);
extern __declspec(dllexport) String __ReverseCallFunc32(void);
extern __declspec(dllexport) String __ReverseCallFunc33(void);
extern __declspec(dllexport) String __ReverseCallFuncEnum(void);
extern __declspec(dllexport) void __ReverseCall(String* test);

#ifdef __cplusplus
}
#endif
